# Consistency Engine Service Configuration
service_name: "consistency-engine"
environment: "${ENVIRONMENT:-development}"

# Database configuration
database:
  default:
    host: "${CONSISTENCY_ENGINE_DB_HOST:-localhost}"
    port: ${CONSISTENCY_ENGINE_DB_PORT:-5432}
    name: "${CONSISTENCY_ENGINE_DB_NAME:-marty_consistency}"
    user: "${CONSISTENCY_ENGINE_DB_USER:-marty_user}"
    password: "${CONSISTENCY_ENGINE_DB_PASSWORD:-marty_password}"
    pool_size: ${CONSISTENCY_ENGINE_DB_POOL_SIZE:-20}
    max_overflow: ${CONSISTENCY_ENGINE_DB_MAX_OVERFLOW:-30}

# Consistency Engine specific configuration
consistency_engine:
  # Processing configuration
  max_concurrent_checks: ${CONSISTENCY_ENGINE_MAX_CONCURRENT:-50}
  processing_timeout: ${CONSISTENCY_ENGINE_TIMEOUT:-60}
  validation_mode: "${CONSISTENCY_VALIDATION_MODE:-strict}"
  
  # Consistency rules configuration
  consistency_rules:
    default_fuzzy_threshold: ${CONSISTENCY_DEFAULT_FUZZY_THRESHOLD:-0.8}
    enable_cross_validation: ${CONSISTENCY_ENABLE_CROSS_VALIDATION:-true}
    enable_checksum_validation: ${CONSISTENCY_ENABLE_CHECKSUM:-true}
    enable_date_validation: ${CONSISTENCY_ENABLE_DATE_VALIDATION:-true}
    strict_exact_match: ${CONSISTENCY_STRICT_EXACT_MATCH:-true}
    
    # Rule-specific thresholds
    fuzzy_match_threshold: ${CONSISTENCY_FUZZY_THRESHOLD:-0.8}
    name_similarity_threshold: ${CONSISTENCY_NAME_SIMILARITY:-0.85}
    critical_mismatch_threshold: ${CONSISTENCY_CRITICAL_THRESHOLD:-0.7}
    
  # Field mappings configuration
  field_mappings:
    strict_validation: ${CONSISTENCY_STRICT_FIELD_VALIDATION:-true}
    normalize_dates: ${CONSISTENCY_NORMALIZE_DATES:-true}
    normalize_names: ${CONSISTENCY_NORMALIZE_NAMES:-true}
    case_insensitive_matching: ${CONSISTENCY_CASE_INSENSITIVE:-true}
    
    # Data normalization settings
    date_formats: ["YYYY-MM-DD", "DD/MM/YYYY", "MM/DD/YYYY", "YYMMDD", "DDMMYY"]
    name_normalization: true
    whitespace_normalization: true
    special_char_handling: true
    
  # Performance settings
  performance:
    max_concurrent_checks: ${CONSISTENCY_MAX_CONCURRENT:-100}
    processing_timeout_seconds: ${CONSISTENCY_PROCESSING_TIMEOUT:-30}
    audit_retention_days: ${CONSISTENCY_AUDIT_RETENTION:-90}
    enable_parallel_rule_execution: ${CONSISTENCY_PARALLEL_RULES:-true}
    cache_field_mappings: ${CONSISTENCY_CACHE_MAPPINGS:-true}
    cache_consistency_rules: ${CONSISTENCY_CACHE_RULES:-true}
    
  # Audit and compliance
  audit:
    enable_audit_trail: ${CONSISTENCY_ENABLE_AUDIT:-true}
    detailed_audit_logging: ${CONSISTENCY_DETAILED_AUDIT:-true}
    store_normalized_data: ${CONSISTENCY_STORE_NORMALIZED:-false}
    audit_retention_policy: "${CONSISTENCY_AUDIT_POLICY:-automated}"
    
  # Integration settings
  integration:
    cedar_policy_engine_enabled: ${CONSISTENCY_CEDAR_ENABLED:-true}
    external_validation_enabled: ${CONSISTENCY_EXTERNAL_VALIDATION:-false}
    real_time_validation: ${CONSISTENCY_REAL_TIME:-true}

# Cedar Policy Engine configuration
cedar_policy_engine:
  enabled: ${CEDAR_POLICY_ENGINE_ENABLED:-true}
  schema_path: "${CEDAR_SCHEMA_PATH:-/app/config/cedar_schema.cedarschema}"
  policies_path: "${CEDAR_POLICIES_PATH:-/app/config/policy.yaml}"
  validation_mode: "${CEDAR_VALIDATION_MODE:-strict}"

# Redis configuration for caching
redis:
  host: "${REDIS_HOST:-localhost}"
  port: ${REDIS_PORT:-6379}
  password: "${REDIS_PASSWORD:-}"
  database: ${REDIS_DATABASE:-0}
  ssl_enabled: ${REDIS_SSL_ENABLED:-false}
  connection_pool_size: ${REDIS_POOL_SIZE:-10}
  
  # Cache settings
  cache:
    field_mappings_ttl: ${REDIS_FIELD_MAPPINGS_TTL:-3600}  # 1 hour
    consistency_rules_ttl: ${REDIS_CONSISTENCY_RULES_TTL:-7200}  # 2 hours
    normalized_data_ttl: ${REDIS_NORMALIZED_DATA_TTL:-300}  # 5 minutes

# gRPC server configuration
grpc:
  server:
    host: "${CONSISTENCY_ENGINE_GRPC_HOST:-0.0.0.0}"
    port: ${CONSISTENCY_ENGINE_GRPC_PORT:-50051}
    max_workers: ${CONSISTENCY_ENGINE_GRPC_MAX_WORKERS:-20}
    reflection_enabled: ${CONSISTENCY_ENGINE_GRPC_REFLECTION:-true}
    max_message_length: ${CONSISTENCY_ENGINE_GRPC_MAX_MESSAGE:-16777216}  # 16MB

# REST API configuration
rest_api:
  enabled: ${CONSISTENCY_ENGINE_REST_ENABLED:-true}
  host: "${CONSISTENCY_ENGINE_REST_HOST:-0.0.0.0}"
  port: ${CONSISTENCY_ENGINE_REST_PORT:-8080}
  cors_enabled: ${CONSISTENCY_ENGINE_CORS_ENABLED:-true}
  cors_origins: "${CONSISTENCY_ENGINE_CORS_ORIGINS:-*}"

# Service discovery configuration
service_discovery:
  hosts:
    consistency_engine: "${CONSISTENCY_ENGINE_HOST:-consistency-engine}"
    cedar_policy_engine: "${CEDAR_POLICY_ENGINE_HOST:-consistency-engine}"
    redis: "${REDIS_HOST:-redis}"
    
  ports:
    consistency_engine: ${CONSISTENCY_ENGINE_PORT:-50051}
    cedar_policy_engine: ${CEDAR_POLICY_ENGINE_PORT:-50051}
    redis: ${REDIS_PORT:-6379}

# CRITICAL: Unified observability configuration
monitoring:
  metrics:
    enabled: true
    port: 8080
    path: "/metrics"
    business_metrics:
      # Consistency check operations
      consistency_operations:
        enabled: true
        labels: ["operation", "zone_count", "rule_count", "result"]
        description: "Consistency check operation metrics"
        
      # Rule execution metrics
      rule_execution:
        enabled: true
        labels: ["rule_type", "rule_id", "result", "execution_time_category"]
        description: "Consistency rule execution metrics"
        
      # Field validation metrics
      field_validation:
        enabled: true
        labels: ["field_type", "zone_pair", "validation_type", "result"]
        description: "Field validation and mapping metrics"
        
      # Cross-zone consistency metrics
      cross_zone_consistency:
        enabled: true
        labels: ["source_zone", "target_zone", "field_name", "consistency_result"]
        description: "Cross-zone data consistency metrics"
        
      # Data quality metrics
      data_quality:
        enabled: true
        labels: ["quality_metric", "zone", "severity", "confidence_level"]
        description: "Data quality assessment metrics"
        
      # Fuzzy matching metrics
      fuzzy_matching:
        enabled: true
        labels: ["match_type", "similarity_range", "field_type", "result"]
        description: "Fuzzy matching algorithm performance"
        
      # Audit trail metrics
      audit_trail:
        enabled: true
        labels: ["audit_operation", "status", "retention_policy", "data_category"]
        description: "Audit trail and compliance metrics"
        
      # Performance metrics
      performance:
        enabled: true
        labels: ["operation_type", "complexity", "parallel_execution", "cache_hit"]
        description: "Performance and optimization metrics"
        
      # Error and failure metrics
      error_tracking:
        enabled: true
        labels: ["error_type", "component", "severity", "recovery_status"]
        description: "Error tracking and failure analysis"
        
  tracing:
    enabled: true
    service_name: "consistency-engine"
    jaeger_endpoint: "${JAEGER_ENDPOINT:-http://jaeger:14268/api/traces}"
    correlation_id:
      enabled: true
      header: "x-correlation-id"
    sampling:
      type: "probabilistic"
      rate: ${CONSISTENCY_ENGINE_TRACE_SAMPLING:-0.4}  # 40% sampling for consistency workflows
      
  health_checks:
    enabled: true
    endpoint: "/health"
    checks:
      database:
        interval: 30
        timeout: 10
      redis:
        interval: 45
        timeout: 10
      cedar_policy_engine:
        interval: 60
        timeout: 15
      field_mappings:
        interval: 120
        timeout: 5
      consistency_rules:
        interval: 120
        timeout: 5
        
  logging:
    structured: true
    correlation_aware: true
    level: "${LOG_LEVEL:-INFO}"
    format: "json"
    fields:
      service: "consistency-engine"
      component: "cross_zone_validation"

# Business metrics configuration
business_metrics:
  # Validation tracking
  validation:
    track_consistency_checks: true
    track_rule_execution_time: true
    track_field_validation_accuracy: true
    track_cross_zone_discrepancies: true
    
  # Quality monitoring
  quality:
    track_data_quality_scores: true
    track_confidence_levels: true
    track_critical_mismatches: true
    track_validation_coverage: true
    
  # Performance monitoring
  performance:
    track_processing_time: true
    track_throughput: true
    track_parallel_execution: true
    track_cache_performance: true
    
  # Audit and compliance
  audit:
    track_audit_trail_completeness: true
    track_retention_compliance: true
    track_data_lineage: true
    track_policy_violations: true
    
  # Integration monitoring
  integration:
    cedar_policy_engine_performance: true
    database_performance: true
    cache_performance: true
    external_validation_latency: true

# Environment-specific overrides
development:
  consistency_engine:
    max_concurrent_checks: 20
    processing_timeout: 120
    audit:
      detailed_audit_logging: true
  monitoring:
    logging:
      level: "DEBUG"
    tracing:
      sampling:
        rate: 1.0  # 100% sampling in development
        
testing:
  database:
    default:
      name: "marty_consistency_test"
  consistency_engine:
    max_concurrent_checks: 10
    processing_timeout: 30
    validation_mode: "permissive"
    consistency_rules:
      enable_cross_validation: false  # Simplified for testing
  monitoring:
    tracing:
      enabled: false
    logging:
      level: "INFO"
      
production:
  consistency_engine:
    max_concurrent_checks: 200
    processing_timeout: 30
    validation_mode: "strict"
    consistency_rules:
      strict_exact_match: true
      critical_mismatch_threshold: 0.8  # Higher threshold in production
  monitoring:
    tracing:
      jaeger_endpoint: "https://jaeger.marty.example.com/api/traces"
      sampling:
        rate: 0.2  # 20% sampling in production
    logging:
      level: "WARN"
  redis:
    ssl_enabled: true
    host: "redis.marty.example.com"