# Modern Document Signer Service Configuration
# This demonstrates the new unified configuration structure

# Database configuration - per service database
database:
  document_signer:
    host: "${DOCUMENT_SIGNER_DB_HOST:-localhost}"
    port: ${DOCUMENT_SIGNER_DB_PORT:-5432}
    database: "${DOCUMENT_SIGNER_DB_NAME:-marty_document_signer}"
    username: "${DOCUMENT_SIGNER_DB_USER:-doc_signer_user}"
    password: "${DOCUMENT_SIGNER_DB_PASSWORD:-change_me_in_production}"
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600
    ssl_mode: "prefer"
    connection_timeout: 30

# Security configuration
security:
  grpc_tls:
    enabled: true
    mtls: true
    require_client_auth: true
    server_cert: "${TLS_SERVER_CERT:-/etc/tls/server/tls.crt}"
    server_key: "${TLS_SERVER_KEY:-/etc/tls/server/tls.key}"
    client_ca: "${TLS_CLIENT_CA:-/etc/tls/ca/ca.crt}"
    client_cert: "${TLS_CLIENT_CERT:-/etc/tls/client/tls.crt}"
    client_key: "${TLS_CLIENT_KEY:-/etc/tls/client/tls.key}"
    verify_hostname: true

  auth:
    required: true
    jwt_enabled: true
    jwt_algorithm: "HS256"
    jwt_secret: "${JWT_SECRET}"
    api_key_enabled: true
    client_cert_enabled: true
    extract_subject: true

  authz:
    enabled: true
    policy_config: "${AUTHZ_POLICY_CONFIG:-/etc/authz/policy.yaml}"
    default_action: "deny"

# Cryptographic configuration
cryptographic:
  signing:
    algorithm: "rsa2048"
    key_id: "document-signer-default"
    key_directory: "${KEY_DIRECTORY:-/app/data/keys}"
    key_rotation_days: 90
    certificate_validity_days: 365

  sd_jwt:
    issuer: "${SD_JWT_ISSUER:-https://issuer.marty.digital}"
    signing_key_id: "document-signer-sdjwt"
    signing_algorithm: "ES256"
    vault_signing_algorithm: "ecdsa-p256"
    certificate_id: "document-signer-default-dsc"
    offer_ttl_seconds: 600
    token_ttl_seconds: 600

  vault:
    url: "${VAULT_ADDR:-https://vault.internal:8200}"
    auth_method: "${VAULT_AUTH_METHOD:-approle}"
    token: "${VAULT_TOKEN:-}"
    role_id: "${VAULT_ROLE_ID:-}"
    secret_id: "${VAULT_SECRET_ID:-}"
    namespace: "${VAULT_NAMESPACE:-}"
    ca_cert: "${VAULT_CACERT:-/secrets/vault/ca.crt}"
    mount_path: "secret"

# Service discovery
service_discovery:
  hosts:
    csca_service: "${CSCA_SERVICE_HOST:-csca-service}"
    pkd_service: "${PKD_SERVICE_HOST:-pkd-service}"
    trust_anchor: "${TRUST_ANCHOR_HOST:-trust-anchor}"
  ports:
    csca_service: ${CSCA_SERVICE_PORT:-8081}
    pkd_service: ${PKD_SERVICE_PORT:-8089}
    trust_anchor: ${TRUST_ANCHOR_PORT:-8080}
  enable_service_mesh: ${ENABLE_SERVICE_MESH:-false}
  service_mesh_namespace: "${SERVICE_MESH_NAMESPACE:-marty}"

# Logging configuration
logging:
  level: "${LOG_LEVEL:-INFO}"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers: ["console"]
  file: "${LOG_FILE:-}"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Monitoring configuration  
monitoring:
  enabled: true
  service_name: "document_signer"
  metrics_port: ${METRICS_PORT:-9090}
  health_check_port: ${HEALTH_CHECK_PORT:-8080}
  
  # Prometheus configuration
  prometheus:
    enabled: true
    path: "/metrics"
    
  # Tracing configuration
  tracing:
    enabled: true
    jaeger_endpoint: "${JAEGER_ENDPOINT:-http://jaeger:14268/api/traces}"
    sampling_rate: ${TRACING_SAMPLING_RATE:-0.1}
    
  # Business metrics configuration
  business_metrics:
    - name: "documents_signed"
      type: "counter"
      description: "Total documents signed"
      labels: ["algorithm", "document_type", "result"]
      
    - name: "document_signing_duration"
      type: "histogram"
      description: "Time to sign documents"
      labels: ["algorithm", "document_type"]
      buckets: [0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0]
      
    - name: "cryptographic_key_operations"
      type: "counter"
      description: "Cryptographic key operations"
      labels: ["operation", "key_type", "result"]
      
    - name: "sd_jwt_operations"
      type: "counter"
      description: "SD-JWT credential operations"
      labels: ["operation", "result"]
      
    - name: "credential_store_operations"
      type: "counter"
      description: "Credential store operations"
      labels: ["operation", "result"]

# Resilience configuration
resilience:
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 60
    half_open_max_calls: 3
  retry_policy:
    max_attempts: 3
    backoff_multiplier: 1.5
    max_delay_seconds: 30

# Service-specific configuration
services:
  document_signer:
    # Document signing specific settings
    max_concurrent_signings: 10
    signing_timeout_seconds: 30
    enable_batch_signing: true
    batch_size: 100
    
    # SD-JWT specific settings
    enable_sd_jwt: true
    x5c_certificate_ids: 
      - "document-signer-default-dsc"
      - "document-signer-backup-dsc"
    
    # Storage settings
    credential_store_ttl_hours: 24
    offer_store_ttl_hours: 1
    
    # Event publishing
    enable_event_publishing: true
    event_topics:
      - "document.signed"
      - "credential.issued"
      - "offer.created"