# Modern Trust Anchor Service Configuration
# This demonstrates trust store and PKD configuration patterns

# Database configuration - per service database
database:
  trust_anchor:
    host: "${TRUST_ANCHOR_DB_HOST:-localhost}"
    port: ${TRUST_ANCHOR_DB_PORT:-5432}
    database: "${TRUST_ANCHOR_DB_NAME:-marty_trust_anchor}"
    username: "${TRUST_ANCHOR_DB_USER:-trust_user}"
    password: "${TRUST_ANCHOR_DB_PASSWORD:-change_me_in_production}"
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600
    ssl_mode: "prefer"
    connection_timeout: 30

# Security configuration
security:
  grpc_tls:
    enabled: true
    mtls: true
    require_client_auth: true
    server_cert: "${TLS_SERVER_CERT:-/etc/tls/server/tls.crt}"
    server_key: "${TLS_SERVER_KEY:-/etc/tls/server/tls.key}"
    client_ca: "${TLS_CLIENT_CA:-/etc/tls/ca/ca.crt}"
    client_cert: "${TLS_CLIENT_CERT:-/etc/tls/client/tls.crt}"
    client_key: "${TLS_CLIENT_KEY:-/etc/tls/client/tls.key}"
    verify_hostname: true

  auth:
    required: true
    jwt_enabled: true
    jwt_algorithm: "HS256"
    jwt_secret: "${JWT_SECRET}"
    api_key_enabled: true
    client_cert_enabled: true
    extract_subject: true

  authz:
    enabled: true
    policy_config: "${AUTHZ_POLICY_CONFIG:-/etc/authz/policy.yaml}"
    default_action: "deny"

# Trust store configuration (Marty-specific)
trust_store:
  trust_anchor:
    certificate_store_path: "${CERT_STORE_PATH:-/app/data/trust}"
    update_interval_hours: ${TRUST_UPDATE_INTERVAL:-24}
    validation_timeout_seconds: ${VALIDATION_TIMEOUT:-30}
    enable_online_verification: ${ENABLE_ONLINE_VERIFICATION:-false}
    backup_store_path: "${BACKUP_CERT_STORE:-/app/data/trust_backup}"
    max_certificate_age_days: ${MAX_CERT_AGE_DAYS:-365}
    
  pkd:
    service_url: "${PKD_SERVICE_URL:-http://pkd-service:8089}"
    enabled: ${PKD_ENABLED:-true}
    update_interval_hours: ${PKD_UPDATE_INTERVAL:-24}
    max_retries: ${PKD_MAX_RETRIES:-3}
    timeout_seconds: ${PKD_TIMEOUT:-30}
    data_directory: "${PKD_DATA_DIR:-/app/data/pkd}"
    synthetic_data_dir: "${SYNTHETIC_DATA_DIR:-/app/data/synthetic}"
    master_list_max_age_hours: ${MASTER_LIST_MAX_AGE:-24}

# Service discovery
service_discovery:
  hosts:
    csca_service: "${CSCA_SERVICE_HOST:-csca-service}"
    document_signer: "${DOCUMENT_SIGNER_HOST:-document-signer}"
    pkd_service: "${PKD_SERVICE_HOST:-pkd-service}"
    inspection_system: "${INSPECTION_SYSTEM_HOST:-inspection-system}"
  ports:
    csca_service: ${CSCA_SERVICE_PORT:-8081}
    document_signer: ${DOCUMENT_SIGNER_PORT:-8082}
    pkd_service: ${PKD_SERVICE_PORT:-8089}
    inspection_system: ${INSPECTION_SYSTEM_PORT:-8083}
  enable_service_mesh: ${ENABLE_SERVICE_MESH:-false}
  service_mesh_namespace: "${SERVICE_MESH_NAMESPACE:-marty}"

# Logging configuration
logging:
  level: "${LOG_LEVEL:-INFO}"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers: ["console"]
  file: "${LOG_FILE:-}"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Monitoring configuration  
monitoring:
  enabled: true
  service_name: "trust_anchor"
  metrics_port: ${METRICS_PORT:-9090}
  health_check_port: ${HEALTH_CHECK_PORT:-8080}
  
  # Prometheus configuration
  prometheus:
    enabled: true
    path: "/metrics"
    
  # Tracing configuration
  tracing:
    enabled: true
    jaeger_endpoint: "${JAEGER_ENDPOINT:-http://jaeger:14268/api/traces}"
    sampling_rate: ${TRACING_SAMPLING_RATE:-0.1}
    
  # Business metrics configuration
  business_metrics:
    - name: "certificate_validations"
      type: "counter"
      description: "Certificate validation operations"
      labels: ["result", "certificate_type", "issuer_country"]
      
    - name: "certificate_validation_duration"
      type: "histogram"
      description: "Time to validate certificates"
      labels: ["certificate_type"]
      buckets: [0.001, 0.01, 0.1, 0.5, 1.0, 5.0]
      
    - name: "trust_chain_length"
      type: "histogram"
      description: "Length of certificate trust chains"
      labels: ["certificate_type"]
      buckets: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      
    - name: "pkd_sync_operations"
      type: "counter"
      description: "PKD synchronization operations"
      labels: ["result", "sync_type"]
      
    - name: "pkd_sync_duration"
      type: "histogram"
      description: "Time to complete PKD sync"
      labels: ["sync_type"]
      buckets: [1, 5, 10, 30, 60, 120, 300]

# Resilience configuration
resilience:
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 60
    half_open_max_calls: 3
  retry_policy:
    max_attempts: 3
    backoff_multiplier: 1.5
    max_delay_seconds: 30

# Service-specific configuration
services:
  trust_anchor:
    # Trust validation settings
    max_concurrent_validations: 20
    validation_timeout_seconds: 30
    enable_caching: true
    cache_ttl_seconds: 3600
    cache_max_size: 10000
    
    # Certificate management
    auto_update_certificates: true
    certificate_refresh_interval_hours: 12
    enable_certificate_revocation_check: true
    
    # PKD integration
    pkd_sync_enabled: true
    pkd_sync_interval_minutes: 30
    pkd_batch_size: 1000
    
    # Trust metrics
    enable_trust_metrics: true
    trust_score_threshold: 0.8
    trust_decay_factor: 0.95
    
    # Event publishing
    enable_event_publishing: true
    event_topics:
      - "trust.certificate.updated"
      - "trust.validation.completed"
      - "pkd.sync.completed"