apiVersion: v2
name: marty-monitoring
description: Monitoring stack for Marty microservices platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: prometheus
    version: "25.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "7.0.0"
    repository: "https://grafana.github.io/helm-charts"
  - name: alertmanager
    version: "1.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"