# Marty Monitoring Stack Configuration

prometheus:
  server:
    configMapOverrideName: "marty-prometheus-config"
    extraArgs:
      enable-feature: expanded-response-metadata
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m

  serverFiles:
    prometheus.yml: |
      global:
        scrape_interval: 15s
        evaluation_interval: 15s

      rule_files:
        - "/etc/config/alert_rules.yml"

      alerting:
        alertmanagers:
          - static_configs:
              - targets:
                - alertmanager:9093

      scrape_configs:
        - job_name: 'csca-service'
          static_configs:
            - targets: ['csca-service.marty.svc.cluster.local:8081']
          metrics_path: '/metrics'
          scrape_interval: 10s

        - job_name: 'document-signer'
          static_configs:
            - targets: ['document-signer.marty.svc.cluster.local:8082']
          metrics_path: '/metrics'
          scrape_interval: 10s

        - job_name: 'inspection-system'
          static_configs:
            - targets: ['inspection-system.marty.svc.cluster.local:8083']
          metrics_path: '/metrics'
          scrape_interval: 10s

        - job_name: 'mdl-engine'
          static_configs:
            - targets: ['mdl-engine.marty.svc.cluster.local:8085']
          metrics_path: '/metrics'
          scrape_interval: 10s

        - job_name: 'mdoc-engine'
          static_configs:
            - targets: ['mdoc-engine.marty.svc.cluster.local:8086']
          metrics_path: '/metrics'
          scrape_interval: 10s

        - job_name: 'passport-engine'
          static_configs:
            - targets: ['passport-engine.marty.svc.cluster.local:8084']
          metrics_path: '/metrics'
          scrape_interval: 10s

        - job_name: 'pkd-service'
          static_configs:
            - targets: ['pkd-service.marty.svc.cluster.local:9090']
          metrics_path: '/metrics'
          scrape_interval: 10s

        - job_name: 'trust-anchor'
          static_configs:
            - targets: ['trust-anchor.marty.svc.cluster.local:9080']
          metrics_path: '/metrics'
          scrape_interval: 10s

    alert_rules.yml: |
      groups:
        - name: marty_service_alerts
          rules:
            - alert: MartyServiceDown
              expr: up{job=~"csca-service|document-signer|inspection-system|mdl-engine|mdoc-engine|passport-engine|pkd-service|trust-anchor"} == 0
              for: 5m
              labels:
                severity: critical
              annotations:
                summary: "Marty service {{ $labels.job }} is down"
                description: "Marty service {{ $labels.job }} has been down for more than 5 minutes."

            - alert: MartyServiceHighErrorRate
              expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: "High error rate on {{ $labels.job }}"
                description: "Error rate for {{ $labels.job }} is {{ $value | printf \"%.2f\" }}% over the last 5 minutes."

            - alert: MartyServiceHighLatency
              expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 5
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: "High latency on {{ $labels.job }}"
                description: "95th percentile latency for {{ $labels.job }} is {{ $value | printf \"%.2f\" }}s over the last 5 minutes."

grafana:
  adminPassword: "admin"  # Change in production
  service:
    type: ClusterIP
    port: 80

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://marty-monitoring-prometheus-server.marty-monitoring.svc.cluster.local
          access: proxy
          isDefault: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'marty'
          orgId: 1
          folder: 'Marty'
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: true
          options:
            path: /var/lib/grafana/dashboards/marty

  dashboards:
    marty:
      marty-overview:
        json: |
          {
            "dashboard": {
              "title": "Marty Platform Overview",
              "tags": ["marty"],
              "timezone": "browser",
              "panels": [
                {
                  "title": "Service Health",
                  "type": "stat",
                  "targets": [
                    {
                      "expr": "up{job=~\"csca-service|document-signer|dtc-engine|inspection-system|mdl-engine|mdoc-engine|passport-engine|pkd-service|trust-anchor|ui-app\"}",
                      "legendFormat": "{{job}}"
                    }
                  ]
                }
              ]
            }
          }

alertmanager:
  config:
    global:
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alerts@marty-platform.com'
      smtp_auth_username: 'alerts@marty-platform.com'
      smtp_auth_password: 'your-smtp-password'

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'email'
      routes:
        - match:
            severity: critical
          receiver: 'email'

    receivers:
      - name: 'email'
        email_configs:
          - to: 'team@marty-platform.com'
            subject: '[Marty] {{ .GroupLabels.alertname }}'
            body: |
              {{ range .Alerts }}
              Alert: {{ .Annotations.summary }}
              Description: {{ .Annotations.description }}
              {{ end }}