version: '3.8'

services:
  openxpki:
    image: whiterabbitsecurity/openxpki:latest
    container_name: marty-openxpki
    restart: unless-stopped
    ports:
      - "8443:443"  # HTTPS
      - "8080:80"   # HTTP
    volumes:
      - ./data/openxpki/config:/etc/openxpki
      - ./data/openxpki/tls:/etc/openxpki/tls
      - ./data/openxpki/ca:/etc/openxpki/ca
      - ./data/openxpki/logs:/var/log/openxpki
    environment:
      - OPENXPKI_REALM=marty
      - OPENXPKI_COUNTRY=US
      - OPENXPKI_STATE=State
      - OPENXPKI_ORG=Marty PKI
      - OPENXPKI_OU=CSCA Management
      - OPENXPKI_CN=Marty CSCA Management
      - OPENXPKI_ADMIN_USER=pkiadmin
      - OPENXPKI_ADMIN_PASSWORD=secret  # Change for production
      - OPENXPKI_DB_USER=openxpki
      - OPENXPKI_DB_PASSWORD=openxpki  # Change for production
    depends_on:
      - openxpki-db

  openxpki-db:
    image: postgres:14
    container_name: marty-openxpki-db
    restart: unless-stopped
    volumes:
      - ./data/openxpki/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=openxpki
      - POSTGRES_PASSWORD=openxpki  # Change for production
      - POSTGRES_DB=openxpki
    ports:
      - "5433:5432"  # Expose on a different port to avoid conflict with local PostgreSQL

networks:
  default:
    name: marty-network