apiVersion: v2
name: marty-monitoring
description: A Helm chart for Marty monitoring stack with Prometheus, Grafana, and Alertmanager
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "7.0.19"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: alertmanager
    version: "1.9.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: alertmanager.enabled

keywords:
  - monitoring
  - prometheus
  - grafana
  - alertmanager
  - observability
  - metrics
  - digital-identity

maintainers:
  - name: Marty Team
    email: devops@marty.com