apiVersion: v1
kind: Service
metadata:
  name: {{ include "marty-service.fullname" . }}
  labels:
    {{- include "marty-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.healthPort }}
      targetPort: {{ .Values.service.healthPort }}
      protocol: TCP
      name: health
  selector:
    {{- include "marty-service.selectorLabels" . | nindent 4 }}