version: '3.8'

services:
  # Jaeger All-in-One for development tracing
  jaeger:
    image: jaegertracing/all-in-one:1.52
    container_name: marty-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      # Jaeger UI
      - "16686:16686"
      # OTLP gRPC receiver
      - "4317:4317"
      # OTLP HTTP receiver
      - "4318:4318"
      # Jaeger native thrift
      - "14268:14268"
      # Jaeger gRPC
      - "14250:14250"
      # Jaeger agent
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      # Zipkin compatibility
      - "9411:9411"
    volumes:
      - jaeger_data:/tmp
    networks:
      - marty-observability
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # OpenTelemetry Collector (optional - for advanced setups)
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: marty-otel-collector
    command: ["--config=/etc/otelcol-contrib/otel-collector.yml"]
    volumes:
      - ./otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml:ro
    ports:
      # OTLP gRPC receiver
      - "4319:4317"
      # OTLP HTTP receiver
      - "4320:4318"
      # Prometheus metrics
      - "8889:8889"
      # Health check
      - "13133:13133"
    depends_on:
      jaeger:
        condition: service_healthy
    networks:
      - marty-observability
    restart: unless-stopped
    profiles:
      - with-collector
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:13133/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  jaeger_data:
    driver: local

networks:
  marty-observability:
    driver: bridge
    name: marty-observability