# Production Security Configuration for Trust Service

# Vault Configuration
vault:
  # Vault server URL
  url: "${VAULT_ADDR:-https://vault.internal:8200}"
  
  # Authentication method (token for dev, approle for production)
  auth_method: "${VAULT_AUTH_METHOD:-approle}"
  
  # Direct token auth (development only)
  token: "${VAULT_TOKEN:-}"
  
  # AppRole authentication (production)
  role_id: "${VAULT_ROLE_ID:-}"
  secret_id: "${VAULT_SECRET_ID:-}"
  
  # Vault namespace (for Vault Enterprise)
  namespace: "${VAULT_NAMESPACE:-}"
  
  # TLS configuration
  ca_cert: "${VAULT_CACERT:-/secrets/vault/ca.crt}"
  verify_ssl: true
  
  # Secret engine mount points
  mount_point_kv: "kv"
  mount_point_pki: "pki"
  mount_point_database: "database"
  
  # Connection settings
  timeout: 30
  max_retries: 3
  retry_delay: 1

# Mutual TLS Configuration
mtls:
  # Enable mTLS for gRPC services
  enabled: true
  
  # Require client certificates
  require_client_cert: true
  
  # Verify client certificates
  verify_client_cert: true
  
  # Server certificates (from Vault)
  server_cert_path: "/secrets/tls/server.crt"
  server_key_path: "/secrets/tls/server.key"
  
  # Client CA certificate
  client_ca_path: "/secrets/tls/client-ca.crt"
  
  # Allowed client certificate common names
  allowed_clients:
    - "trust-service-client"
    - "pkd-ingestion-service"
    - "certificate-validation-service"
    - "monitoring-service"
  
  # TLS settings
  min_tls_version: "TLSv1.2"
  cipher_suites: "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256"

# JWT Configuration
jwt:
  # Enable JWT authentication
  enabled: true
  
  # JWT algorithm
  algorithm: "RS256"
  
  # Token expiry
  expiry_minutes: 60
  
  # JWT issuer and audience
  issuer: "trust-service"
  audience: "trust-service-api"
  
  # Key rotation
  key_rotation_days: 30

# API Key Configuration
api_keys:
  # Enable API key authentication
  enabled: true
  
  # API key header name
  header: "X-API-Key"
  
  # API key length
  length: 32
  
  # Key rotation
  rotation_days: 90

# Rate Limiting Configuration
rate_limiting:
  # Enable rate limiting
  enabled: true
  
  # Requests per minute per client
  requests_per_minute: 1000
  
  # Burst size
  burst_size: 100
  
  # Rate limiting by IP
  by_ip: true
  
  # Rate limiting by API key
  by_api_key: true
  
  # Rate limiting by user
  by_user: true

# Database Security Configuration
database_security:
  # SSL/TLS encryption
  ssl_enabled: true
  ssl_mode: "require"  # require, verify-ca, verify-full
  ssl_ca_cert: "/secrets/db/ca.crt"
  ssl_client_cert: "/secrets/db/client.crt"
  ssl_client_key: "/secrets/db/client.key"
  
  # Connection security
  require_ssl: true
  min_tls_version: "TLSv1.2"
  
  # Credential rotation
  credential_rotation_enabled: true
  rotation_check_interval: 300  # 5 minutes
  credential_ttl_hours: 8
  
  # Connection pooling security
  max_connections: 20
  connection_timeout: 30
  idle_timeout: 3600  # 1 hour
  max_lifetime: 7200  # 2 hours
  
  # Audit settings
  audit_enabled: true
  log_connections: true
  log_queries: false  # Careful with sensitive data

# Audit Logging Configuration
audit_logging:
  # Enable audit logging
  enabled: true
  
  # Log destinations
  log_to_file: true
  log_to_database: true
  log_to_siem: false
  
  # Encryption for sensitive data
  encryption_enabled: true
  
  # Retention policy
  retention_days: 365
  
  # Log file settings
  log_file_path: "/var/log/trust-service/audit.log"
  log_file_max_size: "100MB"
  log_file_backup_count: 10
  
  # Events to log
  log_authentication: true
  log_authorization: true
  log_certificate_operations: true
  log_data_access: true
  log_security_events: true
  log_system_events: true
  
  # Sensitive fields to encrypt
  sensitive_fields:
    - "password"
    - "token"
    - "key"
    - "secret"
    - "private_key"

# Security Headers Configuration
security_headers:
  # Enable security headers
  enabled: true
  
  # HSTS settings
  hsts_enabled: true
  hsts_max_age: 31536000  # 1 year
  hsts_include_subdomains: true
  hsts_preload: false
  
  # Content Security Policy
  csp_enabled: true
  csp_policy: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'"
  
  # Other security headers
  x_content_type_options: "nosniff"
  x_frame_options: "DENY"
  x_xss_protection: "1; mode=block"
  referrer_policy: "strict-origin-when-cross-origin"
  permissions_policy: "geolocation=(), microphone=(), camera=()"

# Request Validation Configuration
request_validation:
  # Enable request validation
  enabled: true
  
  # Request size limits
  max_request_size: 10485760  # 10MB
  max_header_size: 8192  # 8KB
  max_query_params: 100
  
  # Request timeout
  request_timeout: 30
  
  # Content type validation
  allowed_content_types:
    - "application/json"
    - "application/protobuf"
    - "application/x-protobuf"
    - "multipart/form-data"
  
  # Input sanitization
  sanitize_input: true
  validate_utf8: true
  
  # SQL injection protection
  sql_injection_protection: true
  
  # XSS protection
  xss_protection: true

# Session Management Configuration
session_management:
  # Session timeout
  timeout_minutes: 480  # 8 hours
  
  # Maximum concurrent sessions per user
  max_concurrent_sessions: 10
  
  # Session storage
  storage_type: "database"  # memory, database, redis
  
  # Session security
  secure_cookies: true
  http_only_cookies: true
  same_site: "strict"
  
  # Session rotation
  rotate_on_login: true
  rotate_interval_minutes: 60

# Network Security Configuration
network_security:
  # Allowed IP ranges (CIDR notation)
  allowed_ip_ranges:
    - "10.0.0.0/8"      # Internal network
    - "172.16.0.0/12"   # Internal network
    - "192.168.0.0/16"  # Internal network
  
  # Blocked IP ranges
  blocked_ip_ranges:
    - "0.0.0.0/0"  # Block all by default, then allow specific ranges
  
  # GeoIP filtering
  geoip_enabled: false
  allowed_countries: []
  blocked_countries: []
  
  # DDoS protection
  ddos_protection_enabled: true
  connection_rate_limit: 100  # connections per second
  
  # Firewall rules
  firewall_enabled: true

# Encryption Configuration
encryption:
  # Default encryption algorithm
  algorithm: "AES-256-GCM"
  
  # Key derivation
  kdf: "scrypt"
  kdf_iterations: 100000
  
  # Key rotation
  key_rotation_enabled: true
  key_rotation_days: 90
  
  # Data encryption
  encrypt_at_rest: true
  encrypt_in_transit: true
  encrypt_in_memory: false  # For highly sensitive data
  
  # Backup encryption
  encrypt_backups: true

# Monitoring and Alerting Configuration
security_monitoring:
  # Enable security monitoring
  enabled: true
  
  # Metrics collection
  collect_security_metrics: true
  metrics_interval: 60  # seconds
  
  # Alerting thresholds
  failed_auth_threshold: 5  # per minute
  suspicious_activity_threshold: 10  # per minute
  rate_limit_threshold: 1000  # per minute
  
  # Alert destinations
  alert_webhook_url: "${SECURITY_ALERT_WEBHOOK_URL:-}"
  alert_email: "${SECURITY_ALERT_EMAIL:-}"
  
  # Log analysis
  log_analysis_enabled: true
  anomaly_detection_enabled: true

# Compliance Configuration
compliance:
  # GDPR compliance
  gdpr_enabled: true
  data_retention_days: 365
  right_to_erasure: true
  data_portability: true
  
  # SOC 2 compliance
  soc2_enabled: true
  access_logging: true
  change_management: true
  
  # ISO 27001 compliance
  iso27001_enabled: true
  risk_assessment: true
  incident_response: true
  
  # FIPS 140-2 compliance
  fips_enabled: false
  fips_crypto_module: "openssl-fips"

# Secrets Management Configuration
secrets_management:
  # Automatic secret rotation
  auto_rotation_enabled: true
  
  # Secret types and rotation intervals
  secret_rotation_intervals:
    database_credentials: 480  # 8 hours
    api_keys: 2160  # 90 days
    jwt_keys: 720  # 30 days
    tls_certificates: 17280  # 12 months
  
  # Secret validation
  validate_secrets: true
  secret_strength_requirements:
    min_length: 16
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_symbols: true
  
  # Secret backup and recovery
  backup_secrets: true
  secret_recovery_enabled: true

# Development and Testing Overrides (only for non-production)
development:
  # Disable strict security for development
  relaxed_security: false
  
  # Allow insecure connections
  allow_insecure: false
  
  # Disable certificate validation
  skip_cert_validation: false
  
  # Verbose security logging
  verbose_logging: true
  
  # Test mode
  test_mode: false