services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: marty_db
      POSTGRES_USER: marty_user
      POSTGRES_PASSWORD: marty_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marty_user -d marty_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  trust-anchor:
    build:
      context: ..
      dockerfile: docker/trust-anchor.Dockerfile
    ports:
      - "9080:9080"
    environment:
      - SERVICE_NAME=trust-anchor
      - GRPC_PORT=9080
      - DATA_DIR=/app/data
    volumes:
      - ../data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import socket; s=socket.socket(); s.settimeout(1); s.connect((\"localhost\", 9080)); s.close()'"]
      interval: 10s
      timeout: 5s
      retries: 5

  document-signer:
    build:
      context: ..
      dockerfile: docker/document-signer.Dockerfile
    ports:
      - "9082:9082"
    environment:
      - SERVICE_NAME=document-signer
      - GRPC_PORT=9082
      - DATA_DIR=/app/data
    volumes:
      - ../data:/app/data
    depends_on:
      trust-anchor:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import socket; s=socket.socket(); s.settimeout(1); s.connect((\"localhost\", 9082)); s.close()'"]
      interval: 10s
      timeout: 5s
      retries: 5

  inspection-system:
    build:
      context: ..
      dockerfile: docker/inspection-system.Dockerfile
    ports:
      - "9083:9083"
    environment:
      - SERVICE_NAME=inspection-system
      - GRPC_PORT=9083
      - DATA_DIR=/app/data
    volumes:
      - ../data:/app/data
    depends_on:
      trust-anchor:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import socket; s=socket.socket(); s.settimeout(1); s.connect((\"localhost\", 9083)); s.close()'"]
      interval: 10s
      timeout: 5s
      retries: 5

  passport-engine:
    build:
      context: ..
      dockerfile: docker/passport-engine.Dockerfile
    ports:
      - "9084:9084"
    environment:
      - SERVICE_NAME=passport-engine
      - GRPC_PORT=9084
      - DATA_DIR=/app/data
    volumes:
      - ../data:/app/data
    depends_on:
      document-signer:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import socket; s=socket.socket(); s.settimeout(1); s.connect((\"localhost\", 9084)); s.close()'"]
      interval: 10s
      timeout: 5s
      retries: 5

  ui-app:
    build:
      context: ..
      dockerfile: docker/ui-app.Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SERVICE_NAME=ui-app
      - UI_ENABLE_MOCK_DATA=false
      - UI_PASSPORT_ENGINE_ADDR=passport-engine:9084
      - UI_INSPECTION_SYSTEM_ADDR=inspection-system:9083
      - UI_TRUST_ANCHOR_ADDR=trust-anchor:9080
      - UI_GRPC_TIMEOUT_SECONDS=10
    depends_on:
      passport-engine:
        condition: service_healthy
      inspection-system:
        condition: service_healthy
      trust-anchor:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge