services:
  postgres-test:
    image: postgres:16
    container_name: marty-postgres-test
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ../scripts/init-test-databases.sql:/docker-entrypoint-initdb.d/init-test-databases.sql
    command: >
      postgres
      -c log_statement=all
      -c log_min_duration_statement=0
      -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:

networks:
  default:
    name: marty-test-network
