# Docker Compose override for security hardening
# Use this file to apply security configurations across all services
# Usage: docker-compose -f docker-compose.yml -f docker-compose.security.yml up

version: '3.8'

services:
  postgres:
    # Security hardening for PostgreSQL
    security_opt:
      - no-new-privileges:true
    read_only: false  # Database needs to write
    tmpfs:
      - /var/run/postgresql
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    user: postgres

  trust-svc:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      # Mount data directories as writable
      - trust_data:/app/data:rw
      - trust_logs:/app/logs:rw

  trust-anchor:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      - trust_anchor_data:/app/data:rw
      - trust_anchor_logs:/app/logs:rw

  csca-service:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      - csca_data:/app/data:rw
      - csca_logs:/app/logs:rw

  document-signer:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      - document_signer_data:/app/data:rw
      - document_signer_logs:/app/logs:rw

  inspection-system:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      - inspection_data:/app/data:rw
      - inspection_logs:/app/logs:rw

  passport-engine:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      - passport_engine_data:/app/data:rw
      - passport_engine_logs:/app/logs:rw

  mdl-engine:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      - mdl_engine_data:/app/data:rw
      - mdl_engine_logs:/app/logs:rw

  mdoc-engine:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      - mdoc_engine_data:/app/data:rw
      - mdoc_engine_logs:/app/logs:rw

  dtc-engine:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      - dtc_engine_data:/app/data:rw
      - dtc_engine_logs:/app/logs:rw

  credential-ledger:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      - credential_ledger_data:/app/data:rw
      - credential_ledger_logs:/app/logs:rw

  pkd-service:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      - pkd_service_data:/app/data:rw
      - pkd_service_logs:/app/logs:rw

  ui-app:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    cap_drop:
      - ALL
    user: "1000:1000"
    volumes:
      - ui_app_logs:/app/logs:rw

volumes:
  # Service-specific data volumes
  trust_data:
  trust_logs:
  trust_anchor_data:
  trust_anchor_logs:
  csca_data:
  csca_logs:
  document_signer_data:
  document_signer_logs:
  inspection_data:
  inspection_logs:
  passport_engine_data:
  passport_engine_logs:
  mdl_engine_data:
  mdl_engine_logs:
  mdoc_engine_data:
  mdoc_engine_logs:
  dtc_engine_data:
  dtc_engine_logs:
  credential_ledger_data:
  credential_ledger_logs:
  pkd_service_data:
  pkd_service_logs:
  ui_app_logs:
