global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'trust-svc'
    static_configs:
      - targets: ['trust-svc:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  - job_name: 'trust-svc-health'
    static_configs:
      - targets: ['trust-svc:8080']
    metrics_path: '/api/v1/admin/status'
    scrape_interval: 60s
    scrape_timeout: 5s
    honor_labels: true
