# Demo Service Configuration
service:
  name: "demo-service"
  version: "1.0.0"
  description: "Demo service showing Marty framework patterns"

host: "0.0.0.0"
port: 8080

# Disable gRPC for this simple demo
grpc_enabled: false

app_module: "main:app"

debug: true
reload: true
log_level: "debug"
access_log: true
workers: 1

metrics_enabled: true
metrics_port: 9091