# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inspection_system.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "inspection_system.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17inspection_system.proto\x12\ninspection"\x1e\n\x0eInspectRequest\x12\x0c\n\x04item\x18\x01 \x01(\t"!\n\x0fInspectResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2V\n\x10InspectionSystem\x12\x42\n\x07Inspect\x12\x1a.inspection.InspectRequest\x1a\x1b.inspection.InspectResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "inspection_system_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_INSPECTREQUEST"]._serialized_start = 39
    _globals["_INSPECTREQUEST"]._serialized_end = 69
    _globals["_INSPECTRESPONSE"]._serialized_start = 71
    _globals["_INSPECTRESPONSE"]._serialized_end = 104
    _globals["_INSPECTIONSYSTEM"]._serialized_start = 106
    _globals["_INSPECTIONSYSTEM"]._serialized_end = 192
# @@protoc_insertion_point(module_scope)
