# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

from typing import NoReturn

import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from . import pkd_service_pb2 as pkd__service__pb2

GRPC_GENERATED_VERSION = "1.75.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
         " but the generated code in pkd_service_pb2_grpc.py depends on"
         f" grpcio>={GRPC_GENERATED_VERSION}."
         f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
         f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PKDServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel) -> None:
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTrustAnchors = channel.unary_unary(
            "/pkd.PKDService/ListTrustAnchors",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=pkd__service__pb2.ListTrustAnchorsResponse.FromString,
            _registered_method=True,
        )
        self.Sync = channel.unary_unary(
            "/pkd.PKDService/Sync",
            request_serializer=pkd__service__pb2.SyncRequest.SerializeToString,
            response_deserializer=pkd__service__pb2.SyncResponse.FromString,
            _registered_method=True,
        )


class PKDServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListTrustAnchors(self, request, context) -> NoReturn:
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        msg = "Method not implemented!"
        raise NotImplementedError(msg)

    def Sync(self, request, context) -> NoReturn:
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        msg = "Method not implemented!"
        raise NotImplementedError(msg)


def add_PKDServiceServicer_to_server(servicer, server) -> None:
    rpc_method_handlers = {
        "ListTrustAnchors": grpc.unary_unary_rpc_method_handler(
            servicer.ListTrustAnchors,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=pkd__service__pb2.ListTrustAnchorsResponse.SerializeToString,
        ),
        "Sync": grpc.unary_unary_rpc_method_handler(
            servicer.Sync,
            request_deserializer=pkd__service__pb2.SyncRequest.FromString,
            response_serializer=pkd__service__pb2.SyncResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("pkd.PKDService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("pkd.PKDService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PKDService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTrustAnchors(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pkd.PKDService/ListTrustAnchors",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pkd__service__pb2.ListTrustAnchorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Sync(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pkd.PKDService/Sync",
            pkd__service__pb2.SyncRequest.SerializeToString,
            pkd__service__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
