# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pkd_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "pkd_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11pkd_service.proto\x12\x03pkd\x1a\x1bgoogle/protobuf/empty.proto"\x88\x01\n\x0bTrustAnchor\x12\x16\n\x0e\x63\x65rtificate_id\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x17\n\x0f\x63\x65rtificate_pem\x18\x03 \x01(\t\x12\x13\n\x0bstorage_key\x18\x04 \x01(\t\x12\x11\n\tnot_after\x18\x05 \x01(\t\x12\x0f\n\x07revoked\x18\x06 \x01(\x08"=\n\x18ListTrustAnchorsResponse\x12!\n\x07\x61nchors\x18\x01 \x03(\x0b\x32\x10.pkd.TrustAnchor"$\n\x0bSyncRequest\x12\x15\n\rforce_refresh\x18\x01 \x01(\x08"0\n\x0cSyncResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x84\x01\n\nPKDService\x12I\n\x10ListTrustAnchors\x12\x16.google.protobuf.Empty\x1a\x1d.pkd.ListTrustAnchorsResponse\x12+\n\x04Sync\x12\x10.pkd.SyncRequest\x1a\x11.pkd.SyncResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "pkd_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TRUSTANCHOR"]._serialized_start = 56
    _globals["_TRUSTANCHOR"]._serialized_end = 192
    _globals["_LISTTRUSTANCHORSRESPONSE"]._serialized_start = 194
    _globals["_LISTTRUSTANCHORSRESPONSE"]._serialized_end = 255
    _globals["_SYNCREQUEST"]._serialized_start = 257
    _globals["_SYNCREQUEST"]._serialized_end = 293
    _globals["_SYNCRESPONSE"]._serialized_start = 295
    _globals["_SYNCRESPONSE"]._serialized_end = 343
    _globals["_PKDSERVICE"]._serialized_start = 346
    _globals["_PKDSERVICE"]._serialized_end = 478
# @@protoc_insertion_point(module_scope)
