# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import visa_service_pb2 as visa__service__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in visa_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisaServiceStub(object):
    """Visa Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVisa = channel.unary_unary(
                '/visa_service.VisaService/CreateVisa',
                request_serializer=visa__service__pb2.CreateVisaRequest.SerializeToString,
                response_deserializer=visa__service__pb2.CreateVisaResponse.FromString,
                _registered_method=True)
        self.IssueVisa = channel.unary_unary(
                '/visa_service.VisaService/IssueVisa',
                request_serializer=visa__service__pb2.IssueVisaRequest.SerializeToString,
                response_deserializer=visa__service__pb2.IssueVisaResponse.FromString,
                _registered_method=True)
        self.VerifyVisa = channel.unary_unary(
                '/visa_service.VisaService/VerifyVisa',
                request_serializer=visa__service__pb2.VerifyVisaRequest.SerializeToString,
                response_deserializer=visa__service__pb2.VerifyVisaResponse.FromString,
                _registered_method=True)
        self.GetVisa = channel.unary_unary(
                '/visa_service.VisaService/GetVisa',
                request_serializer=visa__service__pb2.GetVisaRequest.SerializeToString,
                response_deserializer=visa__service__pb2.GetVisaResponse.FromString,
                _registered_method=True)
        self.SearchVisas = channel.unary_unary(
                '/visa_service.VisaService/SearchVisas',
                request_serializer=visa__service__pb2.SearchVisasRequest.SerializeToString,
                response_deserializer=visa__service__pb2.SearchVisasResponse.FromString,
                _registered_method=True)
        self.UpdateVisaStatus = channel.unary_unary(
                '/visa_service.VisaService/UpdateVisaStatus',
                request_serializer=visa__service__pb2.UpdateVisaStatusRequest.SerializeToString,
                response_deserializer=visa__service__pb2.UpdateVisaStatusResponse.FromString,
                _registered_method=True)
        self.RevokeVisa = channel.unary_unary(
                '/visa_service.VisaService/RevokeVisa',
                request_serializer=visa__service__pb2.RevokeVisaRequest.SerializeToString,
                response_deserializer=visa__service__pb2.RevokeVisaResponse.FromString,
                _registered_method=True)
        self.RenewVisa = channel.unary_unary(
                '/visa_service.VisaService/RenewVisa',
                request_serializer=visa__service__pb2.RenewVisaRequest.SerializeToString,
                response_deserializer=visa__service__pb2.RenewVisaResponse.FromString,
                _registered_method=True)
        self.CreateVisasBatch = channel.unary_unary(
                '/visa_service.VisaService/CreateVisasBatch',
                request_serializer=visa__service__pb2.CreateVisasBatchRequest.SerializeToString,
                response_deserializer=visa__service__pb2.CreateVisasBatchResponse.FromString,
                _registered_method=True)
        self.VerifyVisasBatch = channel.unary_unary(
                '/visa_service.VisaService/VerifyVisasBatch',
                request_serializer=visa__service__pb2.VerifyVisasBatchRequest.SerializeToString,
                response_deserializer=visa__service__pb2.VerifyVisasBatchResponse.FromString,
                _registered_method=True)
        self.GetVisaStatistics = channel.unary_unary(
                '/visa_service.VisaService/GetVisaStatistics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=visa__service__pb2.VisaStatisticsResponse.FromString,
                _registered_method=True)
        self.GetExpiringVisas = channel.unary_unary(
                '/visa_service.VisaService/GetExpiringVisas',
                request_serializer=visa__service__pb2.GetExpiringVisasRequest.SerializeToString,
                response_deserializer=visa__service__pb2.GetExpiringVisasResponse.FromString,
                _registered_method=True)


class VisaServiceServicer(object):
    """Visa Service Definition
    """

    def CreateVisa(self, request, context):
        """Create a new visa
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueVisa(self, request, context):
        """Issue a visa (finalize)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyVisa(self, request, context):
        """Verify a visa
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVisa(self, request, context):
        """Get visa by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVisas(self, request, context):
        """Search visas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVisaStatus(self, request, context):
        """Update visa status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeVisa(self, request, context):
        """Revoke visa
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewVisa(self, request, context):
        """Renew visa
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVisasBatch(self, request, context):
        """Batch operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyVisasBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVisaStatistics(self, request, context):
        """Reports
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExpiringVisas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVisa': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVisa,
                    request_deserializer=visa__service__pb2.CreateVisaRequest.FromString,
                    response_serializer=visa__service__pb2.CreateVisaResponse.SerializeToString,
            ),
            'IssueVisa': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueVisa,
                    request_deserializer=visa__service__pb2.IssueVisaRequest.FromString,
                    response_serializer=visa__service__pb2.IssueVisaResponse.SerializeToString,
            ),
            'VerifyVisa': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyVisa,
                    request_deserializer=visa__service__pb2.VerifyVisaRequest.FromString,
                    response_serializer=visa__service__pb2.VerifyVisaResponse.SerializeToString,
            ),
            'GetVisa': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVisa,
                    request_deserializer=visa__service__pb2.GetVisaRequest.FromString,
                    response_serializer=visa__service__pb2.GetVisaResponse.SerializeToString,
            ),
            'SearchVisas': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVisas,
                    request_deserializer=visa__service__pb2.SearchVisasRequest.FromString,
                    response_serializer=visa__service__pb2.SearchVisasResponse.SerializeToString,
            ),
            'UpdateVisaStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVisaStatus,
                    request_deserializer=visa__service__pb2.UpdateVisaStatusRequest.FromString,
                    response_serializer=visa__service__pb2.UpdateVisaStatusResponse.SerializeToString,
            ),
            'RevokeVisa': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeVisa,
                    request_deserializer=visa__service__pb2.RevokeVisaRequest.FromString,
                    response_serializer=visa__service__pb2.RevokeVisaResponse.SerializeToString,
            ),
            'RenewVisa': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewVisa,
                    request_deserializer=visa__service__pb2.RenewVisaRequest.FromString,
                    response_serializer=visa__service__pb2.RenewVisaResponse.SerializeToString,
            ),
            'CreateVisasBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVisasBatch,
                    request_deserializer=visa__service__pb2.CreateVisasBatchRequest.FromString,
                    response_serializer=visa__service__pb2.CreateVisasBatchResponse.SerializeToString,
            ),
            'VerifyVisasBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyVisasBatch,
                    request_deserializer=visa__service__pb2.VerifyVisasBatchRequest.FromString,
                    response_serializer=visa__service__pb2.VerifyVisasBatchResponse.SerializeToString,
            ),
            'GetVisaStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVisaStatistics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=visa__service__pb2.VisaStatisticsResponse.SerializeToString,
            ),
            'GetExpiringVisas': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExpiringVisas,
                    request_deserializer=visa__service__pb2.GetExpiringVisasRequest.FromString,
                    response_serializer=visa__service__pb2.GetExpiringVisasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'visa_service.VisaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('visa_service.VisaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisaService(object):
    """Visa Service Definition
    """

    @staticmethod
    def CreateVisa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/CreateVisa',
            visa__service__pb2.CreateVisaRequest.SerializeToString,
            visa__service__pb2.CreateVisaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssueVisa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/IssueVisa',
            visa__service__pb2.IssueVisaRequest.SerializeToString,
            visa__service__pb2.IssueVisaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyVisa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/VerifyVisa',
            visa__service__pb2.VerifyVisaRequest.SerializeToString,
            visa__service__pb2.VerifyVisaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVisa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/GetVisa',
            visa__service__pb2.GetVisaRequest.SerializeToString,
            visa__service__pb2.GetVisaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVisas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/SearchVisas',
            visa__service__pb2.SearchVisasRequest.SerializeToString,
            visa__service__pb2.SearchVisasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVisaStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/UpdateVisaStatus',
            visa__service__pb2.UpdateVisaStatusRequest.SerializeToString,
            visa__service__pb2.UpdateVisaStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeVisa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/RevokeVisa',
            visa__service__pb2.RevokeVisaRequest.SerializeToString,
            visa__service__pb2.RevokeVisaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewVisa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/RenewVisa',
            visa__service__pb2.RenewVisaRequest.SerializeToString,
            visa__service__pb2.RenewVisaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVisasBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/CreateVisasBatch',
            visa__service__pb2.CreateVisasBatchRequest.SerializeToString,
            visa__service__pb2.CreateVisasBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyVisasBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/VerifyVisasBatch',
            visa__service__pb2.VerifyVisasBatchRequest.SerializeToString,
            visa__service__pb2.VerifyVisasBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVisaStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/GetVisaStatistics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            visa__service__pb2.VisaStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExpiringVisas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visa_service.VisaService/GetExpiringVisas',
            visa__service__pb2.GetExpiringVisasRequest.SerializeToString,
            visa__service__pb2.GetExpiringVisasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
