# Example configuration file demonstrating per-service database configuration

# Development environment configuration with per-service databases
# Uses YAML anchors to inherit common patterns and reduce duplication

# Development-specific hosts
dev_hosts: &dev_hosts
  csca_service: localhost
  document_signer: localhost
  passport_engine: localhost
  inspection_system: localhost
  trust_anchor: localhost
  mdl_engine: localhost
  mdoc_engine: localhost
  dtc_engine: localhost
  credential_ledger: localhost
  pkd_service: localhost

# Service ports
ports: &default_ports
  csca_service: 8081
  document_signer: 8082
  passport_engine: 8084
  inspection_system: 8083
  trust_anchor: 8080
  mdl_engine: 8085
  mdoc_engine: 8086
  dtc_engine: 8087
  credential_ledger: 8088
  pkd_service: 8089

# Service hosts
hosts: *dev_hosts

# Development security settings (more permissive)
security:
  grpc_tls:
    enabled: false  # Disabled for development
    mtls: false
    require_client_auth: false
  
  auth:
    required: false  # Optional authentication in development
    jwt:
      enabled: false
      algorithm: "HS256"
      secret: "dev_jwt_secret_123456789012345678901234"
    client_cert:
      enabled: false
  
  authz:
    enabled: false  # Disabled for development

# Per-service database configuration
# Each service can have its own database for proper data boundaries
database:
  # Default database for services that don't specify their own
  default:
    url: "${MARTY_DATABASE_URL:-postgresql+asyncpg://dev_user:dev_password@localhost:5432/marty_dev}"
    host: localhost
    port: 5432
    user: dev_user
    password: dev_password
    name: marty_dev
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

  # Document Signer service database
  document_signer:
    url: "${MARTY_DOCUMENT_SIGNER_DB_URL:-postgresql+asyncpg://dev_user:dev_password@localhost:5432/marty_document_signer}"
    host: localhost
    port: 5432
    user: dev_user
    password: dev_password
    name: marty_document_signer
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

  # CSCA service database
  csca_service:
    url: "${MARTY_CSCA_DB_URL:-postgresql+asyncpg://dev_user:dev_password@localhost:5432/marty_csca}"
    host: localhost
    port: 5432
    user: dev_user
    password: dev_password
    name: marty_csca
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

  # PKD service database  
  pkd_service:
    url: "${MARTY_PKD_DB_URL:-postgresql+asyncpg://dev_user:dev_password@localhost:5432/marty_pkd}"
    host: localhost
    port: 5432
    user: dev_user
    password: dev_password
    name: marty_pkd
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

  # Passport Engine service database
  passport_engine:
    url: "${MARTY_PASSPORT_ENGINE_DB_URL:-postgresql+asyncpg://dev_user:dev_password@localhost:5432/marty_passport_engine}"
    host: localhost
    port: 5432
    user: dev_user
    password: dev_password
    name: marty_passport_engine
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

# Rest of configuration remains the same...
monitoring:
  metrics_enabled: true
  health_check_enabled: true
  prometheus_port: 9090

# Object storage
object_storage:
  bucket: "marty-dev"
  access_key: "localdev"
  secret_key: "localdev"
  region: "us-east-1"
  endpoint_url: "${MARTY_OBJECT_STORE_ENDPOINT:-http://localhost:9000}"
  secure: false