# Development environment configuration
# Uses YAML anchors to inherit common patterns and reduce duplication

# Development-specific hosts
dev_hosts: &dev_hosts
  csca_service: localhost
  document_signer: localhost
  passport_engine: localhost
  inspection_system: localhost
  trust_anchor: localhost
  mdl_engine: localhost
  mdoc_engine: localhost
  dtc_engine: localhost
  credential_ledger: localhost
  pkd_service: localhost

# Service ports (inherited from base patterns)
ports: &default_ports
  csca_service: 8081
  document_signer: 8082
  passport_engine: 8084
  inspection_system: 8083
  trust_anchor: 8080
  mdl_engine: 8085
  mdoc_engine: 8086
  dtc_engine: 8087
  credential_ledger: 8088
  pkd_service: 8089

# Service hosts
hosts: *dev_hosts

# Development security settings (more permissive)
security:
  grpc_tls:
    enabled: false  # Disabled for development
    mtls: false
    require_client_auth: false

  auth:
    required: false  # Optional authentication in development
    jwt:
      enabled: false
      algorithm: "HS256"
      secret: "dev_jwt_secret_123456789012345678901234"
    client_cert:
      enabled: false

  authz:
    enabled: false  # Disabled for development
    default_action: "allow"  # Permissive for development

# Common service configuration with development overrides
services:
  document_signer:
    signing_algorithm: rsa2048
    signing_key_id: document-signer-default
    sd_jwt:
      issuer: "https://issuer.dev.marty"
      signing_key_id: document-signer-sdjwt
      signing_algorithm: ES256
      vault_signing_algorithm: ecdsa-p256
      certificate_id: document-signer-default-dsc
      offer_ttl_seconds: 600
      token_ttl_seconds: 600

  trust_anchor:
    certificate_store_path: "/app/data/trust"
    update_interval_hours: 24
    validation_timeout_seconds: 30

  inspection_system:
    max_concurrent_inspections: 10
    inspection_timeout_seconds: 300
    enable_biometric_verification: true

# Development-specific logging (more verbose)
logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - console
  file: logs/dev.log

# Development security (ENFORCED - NO EXCEPTIONS)
security:
  grpc_tls:
    enabled: true  # ALWAYS enabled for security
    mtls: true
    require_client_auth: true
    server_cert: "/etc/tls/server/tls.crt"
    server_key: "/etc/tls/server/tls.key"
    client_ca: "/etc/tls/ca/ca.crt"
    client_cert: "/etc/tls/client/tls.crt"
    client_key: "/etc/tls/client/tls.key"

  auth:
    required: true  # ALWAYS required
    jwt:
      enabled: true
      algorithm: "HS256"
      secret: "dev_jwt_secret_123456789012345678901234"
    client_cert:
      enabled: true

  authz:
    enabled: true  # ALWAYS enabled
    default_action: "deny"  # ALWAYS deny by default

  key_directory: 'data/keys'
  key_rotation_days: 90
  certificate_validity_days: 365

# Database configuration - per service databases
database:
  document_signer:
    url: "${DOCUMENT_SIGNER_DATABASE_URL:-postgresql+asyncpg://dev_user:dev_password@localhost:5432/marty_document_signer}"
    host: localhost
    port: 5432
    user: dev_user
    password: dev_password
    name: marty_document_signer
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

  csca:
    url: "${CSCA_DATABASE_URL:-postgresql+asyncpg://dev_user:dev_password@localhost:5432/marty_csca}"
    host: localhost
    port: 5432
    user: dev_user
    password: dev_password
    name: marty_csca
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

  pkd_service:
    url: "${PKD_SERVICE_DATABASE_URL:-postgresql+asyncpg://dev_user:dev_password@localhost:5432/marty_pkd}"
    host: localhost
    port: 5432
    user: dev_user
    password: dev_password
    name: marty_pkd
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

  passport_engine:
    url: "${PASSPORT_ENGINE_DATABASE_URL:-postgresql+asyncpg://dev_user:dev_password@localhost:5432/marty_passport_engine}"
    host: localhost
    port: 5432
    user: dev_user
    password: dev_password
    name: marty_passport_engine
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

# Monitoring configuration
monitoring:
  metrics_enabled: true
  health_check_enabled: true
  prometheus_port: 9090

# Object storage
object_storage:
  bucket: "marty-dev"
  access_key: "localdev"
  secret_key: "localdev"
  region: "us-east-1"
  endpoint_url: "${MARTY_OBJECT_STORE_ENDPOINT:-http://localhost:9000}"
  secure: false
  path_style_access: true

# Key vault
key_vault:
  provider: "${MARTY_KEY_VAULT_PROVIDER:-file}"
  file_path: "data/keys"
  hsm_config_path: "${MARTY_HSM_CONFIG:-}"

# Event bus
event_bus:
  enabled: true
  brokers: "localhost:9092"
  client_id: "marty-dev"
  topic_prefix: "dev."
  consumer_group: "marty-ledger"
  auto_offset_reset: "earliest"

# Feature flags
features:
  enable_debug_endpoints: true
  enable_performance_tracking: true
  enable_detailed_logging: true

# CSCA & Master List Management Configuration
csca_master_list:
  # Paths for local storage
  local_trust_store_path: "data/trust/csca"
  local_crl_path: "data/trust/crls"

  # Certificate monitoring settings
  cert_check_interval_hours: 24
  cert_expiry_warning_days: 90

  # Synchronization settings
  sync_interval_hours: 24

  # Trusted sources for auto-update
  trusted_sources:
    icao:
      type: "icao_pkd"
      url: "https://pkddownloadsg.icao.int/download/masterlist"
      username: "your_pkd_username"
      password: "your_pkd_password"
      ignore_ssl: false

    usa:
      type: "national_site"
      url: "https://csca.state.gov/masterlist"
      format: "asn1"

    local_backup:
      type: "file"
      path: "data/trust/backup/masterlist.ml"

  # Notification settings
  notifications:
    email:
      enabled: true
      smtp_server: "smtp.example.com"
      smtp_port: 587
      from_address: "csca-alerts@example.com"
      to_addresses: ["admin@example.com"]

    webhook:
      enabled: false
      url: "https://example.com/webhook"
      auth_token: ""

# OpenXPKI Integration Settings
openxpki:
  base_url: "https://openxpki.local/api/v2"
  username: "pkiadmin"
  password: "secret"
  realm: "marty"
  connection_timeout: 30
  read_timeout: 60
  # Certificate sync settings
  sync_to_local: true
  local_store_path: "data/trust/openxpki_sync"
  trust_sync_interval_hours: 6

# MDL & MDoc Engine Configuration
mdl_engine:
  host: "localhost"
  port: 50051
  # Add other MDL Engine specific configurations here

mdoc_engine:
  host: "localhost"
  port: 50054 # As used in integration tests
  document_signer_service_name: "document-signer"
  # Add other MDoc Engine specific configurations here

dtc_engine:
  host: "localhost"
  port: 50060
  # Add other DTC Engine specific configurations here
