# Example resilience configuration for production environment
service_name: "marty_service"
environment: "production"

# General settings
enable_metrics: true
enable_health_checks: true
enable_request_logging: false    # Reduce log volume in production
max_concurrent_requests: 200
request_timeout_seconds: 30.0

# Circuit breaker configuration
circuit_breaker:
  failure_threshold: 5           # Stricter threshold in production
  recovery_timeout: 30.0         # Standard recovery time
  half_open_success_threshold: 3 # Require more successes to close
  failure_reset_timeout: 120.0   # Longer reset timeout
  max_concurrent_requests: 20
  enable_metrics: true

# Retry configuration
retry:
  max_attempts: 5
  base_delay: 0.2                # 200ms base delay
  max_delay: 60.0                # 1 minute max delay
  total_timeout: 300.0           # 5 minute total timeout
  backoff_strategy: "exponential_jitter"
  jitter_factor: 0.1
  multiplier: 2.0
  enable_circuit_breaker: true
  enable_adaptive_delays: true   # Enable adaptive delays in production
  success_rate_threshold: 0.85
  failure_window_size: 200
  max_concurrent_retries: 100
  retry_on_exceptions:
    - "ConnectionError"
    - "TimeoutError"
    - "OSError"
  abort_on_exceptions:
    - "ValueError"
    - "TypeError"
    - "KeyError"

# Failure injection (disabled in production)
failure_injection:
  enabled: false
  base_failure_rate: 0.0
  method_specific_rates: {}
  target_metadata_key: "x-failure-inject"
