groups:
  - name: marty_sli_recording_rules
    interval: 30s
    rules:
      # Request rate recording rules
      - record: marty:grpc_request_rate
        expr: sum(rate(marty_grpc_requests_total[5m])) by (service_name)
        labels:
          sli_type: "request_rate"

      - record: marty:grpc_request_rate_1h
        expr: sum(rate(marty_grpc_requests_total[1h])) by (service_name)
        labels:
          sli_type: "request_rate"

      - record: marty:grpc_request_rate_24h
        expr: sum(rate(marty_grpc_requests_total[24h])) by (service_name)
        labels:
          sli_type: "request_rate"

      # Error rate recording rules
      - record: marty:grpc_error_rate
        expr: |
          sum(rate(marty_grpc_errors_total[5m])) by (service_name) /
          sum(rate(marty_grpc_requests_total[5m])) by (service_name)
        labels:
          sli_type: "error_rate"

      - record: marty:grpc_error_rate_1h
        expr: |
          sum(rate(marty_grpc_errors_total[1h])) by (service_name) /
          sum(rate(marty_grpc_requests_total[1h])) by (service_name)
        labels:
          sli_type: "error_rate"

      - record: marty:grpc_error_rate_24h
        expr: |
          sum(rate(marty_grpc_errors_total[24h])) by (service_name) /
          sum(rate(marty_grpc_requests_total[24h])) by (service_name)
        labels:
          sli_type: "error_rate"

      # Availability recording rules (based on error rates)
      - record: marty:availability_5m
        expr: |
          (1 - (
            sum(rate(marty_grpc_errors_total[5m])) by (service_name) /
            sum(rate(marty_grpc_requests_total[5m])) by (service_name)
          )) * 100
        labels:
          sli_type: "availability"

      - record: marty:availability_1h
        expr: |
          (1 - (
            sum(rate(marty_grpc_errors_total[1h])) by (service_name) /
            sum(rate(marty_grpc_requests_total[1h])) by (service_name)
          )) * 100
        labels:
          sli_type: "availability"

      - record: marty:availability_24h
        expr: |
          (1 - (
            sum(rate(marty_grpc_errors_total[24h])) by (service_name) /
            sum(rate(marty_grpc_requests_total[24h])) by (service_name)
          )) * 100
        labels:
          sli_type: "availability"

      - record: marty:availability_7d
        expr: |
          (1 - (
            sum(rate(marty_grpc_errors_total[7d])) by (service_name) /
            sum(rate(marty_grpc_requests_total[7d])) by (service_name)
          )) * 100
        labels:
          sli_type: "availability"

      - record: marty:availability_30d
        expr: |
          (1 - (
            sum(rate(marty_grpc_errors_total[30d])) by (service_name) /
            sum(rate(marty_grpc_requests_total[30d])) by (service_name)
          )) * 100
        labels:
          sli_type: "availability"

      # Latency percentile recording rules
      - record: marty:grpc_latency_p50
        expr: |
          histogram_quantile(0.50,
            sum(rate(marty_grpc_request_duration_seconds_bucket[5m])) by (service_name, le)
          )
        labels:
          sli_type: "latency"
          percentile: "p50"

      - record: marty:grpc_latency_p95
        expr: |
          histogram_quantile(0.95,
            sum(rate(marty_grpc_request_duration_seconds_bucket[5m])) by (service_name, le)
          )
        labels:
          sli_type: "latency"
          percentile: "p95"

      - record: marty:grpc_latency_p99
        expr: |
          histogram_quantile(0.99,
            sum(rate(marty_grpc_request_duration_seconds_bucket[5m])) by (service_name, le)
          )
        labels:
          sli_type: "latency"
          percentile: "p99"

      - record: marty:grpc_latency_p99_1h
        expr: |
          histogram_quantile(0.99,
            sum(rate(marty_grpc_request_duration_seconds_bucket[1h])) by (service_name, le)
          )
        labels:
          sli_type: "latency"
          percentile: "p99"

      - record: marty:grpc_latency_p99_24h
        expr: |
          histogram_quantile(0.99,
            sum(rate(marty_grpc_request_duration_seconds_bucket[24h])) by (service_name, le)
          )
        labels:
          sli_type: "latency"
          percentile: "p99"

  - name: marty_business_sli_recording_rules
    interval: 60s
    rules:
      # Document verification success rate
      - record: marty:document_verification_success_rate
        expr: |
          (
            sum(rate(marty_document_verification_attempts_total[5m])) by (service_name, document_type) -
            sum(rate(marty_document_verification_failures_total[5m])) by (service_name, document_type)
          ) /
          sum(rate(marty_document_verification_attempts_total[5m])) by (service_name, document_type) * 100
        labels:
          sli_type: "business_success_rate"

      - record: marty:document_verification_success_rate_1h
        expr: |
          (
            sum(rate(marty_document_verification_attempts_total[1h])) by (service_name, document_type) -
            sum(rate(marty_document_verification_failures_total[1h])) by (service_name, document_type)
          ) /
          sum(rate(marty_document_verification_attempts_total[1h])) by (service_name, document_type) * 100
        labels:
          sli_type: "business_success_rate"

      # Certificate validation success rate
      - record: marty:certificate_validation_success_rate
        expr: |
          (
            sum(rate(marty_certificate_validation_attempts_total[5m])) by (service_name, certificate_type) -
            sum(rate(marty_certificate_validation_errors_total[5m])) by (service_name, certificate_type)
          ) /
          sum(rate(marty_certificate_validation_attempts_total[5m])) by (service_name, certificate_type) * 100
        labels:
          sli_type: "business_success_rate"

      # PKD sync success rate
      - record: marty:pkd_sync_success_rate
        expr: |
          (
            sum(rate(marty_pkd_sync_attempts_total[1h])) by (service_name, source) -
            sum(rate(marty_pkd_sync_failures_total[1h])) by (service_name, source)
          ) /
          sum(rate(marty_pkd_sync_attempts_total[1h])) by (service_name, source) * 100
        labels:
          sli_type: "business_success_rate"

      # RFID read success rate
      - record: marty:rfid_read_success_rate
        expr: |
          (
            sum(rate(marty_rfid_read_attempts_total[5m])) by (service_name, chip_type) -
            sum(rate(marty_rfid_read_failures_total[5m])) by (service_name, chip_type)
          ) /
          sum(rate(marty_rfid_read_attempts_total[5m])) by (service_name, chip_type) * 100
        labels:
          sli_type: "business_success_rate"

  - name: marty_slo_compliance_recording_rules
    interval: 60s
    rules:
      # SLO compliance for 99.9% availability
      - record: marty:slo_availability_compliance
        expr: |
          (marty:availability_24h >= 99.9) * 100
        labels:
          slo_type: "availability"
          slo_target: "99.9"

      - record: marty:slo_availability_compliance_7d
        expr: |
          (marty:availability_7d >= 99.9) * 100
        labels:
          slo_type: "availability"
          slo_target: "99.9"

      - record: marty:slo_availability_compliance_30d
        expr: |
          (marty:availability_30d >= 99.9) * 100
        labels:
          slo_type: "availability"
          slo_target: "99.9"

      # SLO compliance for P99 latency < 2s
      - record: marty:slo_latency_compliance
        expr: |
          (marty:grpc_latency_p99_24h <= 2.0) * 100
        labels:
          slo_type: "latency"
          slo_target: "2s"

      # SLO compliance for error rate < 1%
      - record: marty:slo_error_rate_compliance
        expr: |
          (marty:grpc_error_rate_24h <= 0.01) * 100
        labels:
          slo_type: "error_rate"
          slo_target: "1%"

      # Overall SLO compliance score
      - record: marty:slo_overall_compliance
        expr: |
          (
            marty:slo_availability_compliance +
            marty:slo_latency_compliance +
            marty:slo_error_rate_compliance
          ) / 3
        labels:
          slo_type: "overall"

  - name: marty_error_budget_recording_rules
    interval: 300s  # 5 minutes
    rules:
      # Error budget consumption for availability SLO (99.9%)
      - record: marty:error_budget_availability_consumed
        expr: |
          (1 - (marty:availability_30d / 100)) / 0.001 * 100
        labels:
          error_budget_type: "availability"
          slo_target: "99.9"

      # Error budget remaining for availability
      - record: marty:error_budget_availability_remaining
        expr: |
          100 - marty:error_budget_availability_consumed
        labels:
          error_budget_type: "availability"
          slo_target: "99.9"

      # Error budget burn rate (how fast we're consuming budget)
      - record: marty:error_budget_burn_rate_1h
        expr: |
          (marty:grpc_error_rate_1h / 0.001) * (1/24/30)
        labels:
          error_budget_type: "burn_rate"
          window: "1h"

      - record: marty:error_budget_burn_rate_24h
        expr: |
          (marty:grpc_error_rate_24h / 0.001) * (1/30)
        labels:
          error_budget_type: "burn_rate"
          window: "24h"
