# Trust Service Alerting Rules
# Comprehensive alerting rules for operational, security, and business metrics

groups:
  # === CRITICAL SYSTEM ALERTS ===
  - name: trust-service.critical
    interval: 30s
    rules:
      - alert: TrustServiceDown
        expr: up{job="trust-service"} == 0
        for: 1m
        labels:
          severity: critical
          service: trust-service
          team: platform
        annotations:
          summary: "Trust Service is down"
          description: "Trust Service instance {{ $labels.instance }} has been down for more than 1 minute"
          runbook_url: "https://docs.marty.com/runbooks/trust-service-down"
          dashboard_url: "https://grafana.marty.com/d/trust-service-ops"

      - alert: TrustServiceHighErrorRate
        expr: |
          (
            sum(rate(trust_service_http_requests_total{status_code=~"5.."}[5m])) /
            sum(rate(trust_service_http_requests_total[5m]))
          ) * 100 > 5
        for: 2m
        labels:
          severity: critical
          service: trust-service
          team: platform
        annotations:
          summary: "High error rate in Trust Service"
          description: "Trust Service error rate is {{ $value }}% over the last 5 minutes"
          runbook_url: "https://docs.marty.com/runbooks/high-error-rate"

      - alert: TrustServiceHighLatency
        expr: |
          histogram_quantile(0.95,
            sum(rate(trust_service_http_request_duration_seconds_bucket[5m])) by (le)
          ) > 5
        for: 3m
        labels:
          severity: critical
          service: trust-service
          team: platform
        annotations:
          summary: "High latency in Trust Service"
          description: "Trust Service 95th percentile latency is {{ $value }}s"
          runbook_url: "https://docs.marty.com/runbooks/high-latency"

      - alert: DatabaseConnectionFailure
        expr: trust_service_database_connections_active == 0
        for: 1m
        labels:
          severity: critical
          service: trust-service
          team: platform
        annotations:
          summary: "Database connection failure"
          description: "No active database connections for Trust Service"
          runbook_url: "https://docs.marty.com/runbooks/database-connection-failure"

  # === WARNING SYSTEM ALERTS ===
  - name: trust-service.warning
    interval: 60s
    rules:
      - alert: TrustServiceHighMemoryUsage
        expr: |
          sum(trust_service_memory_usage_bytes) /
          (1024 * 1024 * 1024) > 2
        for: 5m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "High memory usage in Trust Service"
          description: "Trust Service memory usage is {{ $value }}GB"
          runbook_url: "https://docs.marty.com/runbooks/high-memory-usage"

      - alert: TrustServiceHighCPUUsage
        expr: trust_service_cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "High CPU usage in Trust Service"
          description: "Trust Service CPU usage is {{ $value }}%"
          runbook_url: "https://docs.marty.com/runbooks/high-cpu-usage"

      - alert: TrustServiceLowCacheHitRatio
        expr: trust_service_cache_hit_ratio < 0.8
        for: 10m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "Low cache hit ratio"
          description: "Cache hit ratio for {{ $labels.cache_type }} is {{ $value }}"
          runbook_url: "https://docs.marty.com/runbooks/low-cache-hit-ratio"

      - alert: DependencyDegraded
        expr: trust_service_dependency_health == 1
        for: 2m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "Dependency {{ $labels.dependency }} is degraded"
          description: "Dependency {{ $labels.dependency }} ({{ $labels.type }}) is experiencing issues"
          runbook_url: "https://docs.marty.com/runbooks/dependency-degraded"

  # === SECURITY ALERTS ===
  - name: trust-service.security
    interval: 30s
    rules:
      - alert: HighAuthenticationFailureRate
        expr: |
          sum(rate(trust_security_auth_attempts_total{result="failure"}[5m])) > 10
        for: 1m
        labels:
          severity: critical
          service: trust-service
          team: security
          alert_type: security
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is {{ $value }} failures per second"
          runbook_url: "https://docs.marty.com/runbooks/auth-failure-rate"
          dashboard_url: "https://grafana.marty.com/d/trust-service-security"

      - alert: PotentialBruteForceAttack
        expr: |
          sum by (source_ip) (
            rate(trust_security_events_total{event_type="auth_failure"}[5m])
          ) > 5
        for: 2m
        labels:
          severity: critical
          service: trust-service
          team: security
          alert_type: security
        annotations:
          summary: "Potential brute force attack detected"
          description: "High authentication failures from IP {{ $labels.source_ip }}: {{ $value }} failures/sec"
          runbook_url: "https://docs.marty.com/runbooks/brute-force-attack"

      - alert: SuspiciousSecurityEvent
        expr: |
          sum(rate(trust_security_events_total{event_type=~"suspicious|breach_attempt"}[5m])) > 0
        for: 0m
        labels:
          severity: critical
          service: trust-service
          team: security
          alert_type: security
        annotations:
          summary: "Suspicious security event detected"
          description: "Suspicious security activity: {{ $labels.event_type }} from {{ $labels.source_ip }}"
          runbook_url: "https://docs.marty.com/runbooks/suspicious-activity"

      - alert: RateLimitExceeded
        expr: |
          sum(rate(trust_security_rate_limit_exceeded_total[5m])) > 1
        for: 2m
        labels:
          severity: warning
          service: trust-service
          team: security
        annotations:
          summary: "Rate limit exceeded"
          description: "Rate limit exceeded for {{ $labels.client_type }}: {{ $value }} violations/sec"
          runbook_url: "https://docs.marty.com/runbooks/rate-limit-exceeded"

      - alert: VaultOperationFailure
        expr: |
          sum(rate(trust_security_vault_operations_total{status="failure"}[5m])) > 0
        for: 1m
        labels:
          severity: critical
          service: trust-service
          team: security
        annotations:
          summary: "Vault operation failures"
          description: "Vault {{ $labels.operation }} operations failing: {{ $value }} failures/sec"
          runbook_url: "https://docs.marty.com/runbooks/vault-operation-failure"

      - alert: AuditLoggingFailure
        expr: |
          sum(rate(trust_security_audit_events_total[5m])) == 0
        for: 5m
        labels:
          severity: critical
          service: trust-service
          team: security
        annotations:
          summary: "Audit logging failure"
          description: "No audit events logged in the last 5 minutes - potential audit system failure"
          runbook_url: "https://docs.marty.com/runbooks/audit-logging-failure"

  # === CERTIFICATE OPERATION ALERTS ===
  - name: trust-service.certificates
    interval: 60s
    rules:
      - alert: HighCertificateErrorRate
        expr: |
          (
            sum(rate(trust_certificate_errors_total[5m])) /
            sum(rate(trust_certificate_operations_total[5m]))
          ) * 100 > 10
        for: 3m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "High certificate error rate"
          description: "Certificate error rate is {{ $value }}% for {{ $labels.certificate_type }}"
          runbook_url: "https://docs.marty.com/runbooks/certificate-error-rate"

      - alert: CertificateValidationSlow
        expr: |
          histogram_quantile(0.95,
            sum(rate(trust_certificate_validation_duration_seconds_bucket[5m])) by (le, certificate_type)
          ) > 2
        for: 5m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "Slow certificate validation"
          description: "95th percentile validation time for {{ $labels.certificate_type }} is {{ $value }}s"
          runbook_url: "https://docs.marty.com/runbooks/slow-certificate-validation"

      - alert: CertificateExpiringSoon
        expr: |
          count by (certificate_type, issuer_country) (
            trust_certificate_expiry_days_bucket{le="30"}
          ) > 5
        for: 0m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "Certificates expiring soon"
          description: "{{ $value }} {{ $labels.certificate_type }} certificates from {{ $labels.issuer_country }} expire within 30 days"
          runbook_url: "https://docs.marty.com/runbooks/certificate-expiring"

      - alert: CertificateExpiringCritical
        expr: |
          count by (certificate_type, issuer_country) (
            trust_certificate_expiry_days_bucket{le="7"}
          ) > 0
        for: 0m
        labels:
          severity: critical
          service: trust-service
          team: platform
        annotations:
          summary: "Certificates expiring within 7 days"
          description: "{{ $value }} {{ $labels.certificate_type }} certificates from {{ $labels.issuer_country }} expire within 7 days"
          runbook_url: "https://docs.marty.com/runbooks/certificate-expiring-critical"

  # === BUSINESS METRIC ALERTS ===
  - name: trust-service.business
    interval: 300s
    rules:
      - alert: SLAComplianceViolation
        expr: trust_business_sla_compliance_ratio < 0.95
        for: 5m
        labels:
          severity: critical
          service: trust-service
          team: platform
          alert_type: sla
        annotations:
          summary: "SLA compliance violation"
          description: "SLA compliance for {{ $labels.service }} {{ $labels.sla_type }} is {{ $value }}"
          runbook_url: "https://docs.marty.com/runbooks/sla-violation"
          dashboard_url: "https://grafana.marty.com/d/trust-service-business"

      - alert: LowDocumentProcessingVolume
        expr: |
          sum(rate(trust_business_documents_processed_total[1h])) * 3600 < 100
        for: 10m
        labels:
          severity: warning
          service: trust-service
          team: business
        annotations:
          summary: "Low document processing volume"
          description: "Document processing rate is {{ $value }} documents/hour"
          runbook_url: "https://docs.marty.com/runbooks/low-processing-volume"

      - alert: HighDocumentVerificationFailureRate
        expr: |
          (
            sum(rate(trust_business_verification_results_total{result!="valid"}[10m])) /
            sum(rate(trust_business_verification_results_total[10m]))
          ) * 100 > 20
        for: 5m
        labels:
          severity: warning
          service: trust-service
          team: business
        annotations:
          summary: "High document verification failure rate"
          description: "Document verification failure rate is {{ $value }}% for {{ $labels.document_type }}"
          runbook_url: "https://docs.marty.com/runbooks/high-verification-failure"

      - alert: ComplianceCheckFailure
        expr: |
          sum(rate(trust_business_compliance_checks_total{result="failure"}[5m])) > 0
        for: 1m
        labels:
          severity: critical
          service: trust-service
          team: compliance
        annotations:
          summary: "Compliance check failures"
          description: "Compliance check failures for {{ $labels.regulation }}: {{ $value }} failures/sec"
          runbook_url: "https://docs.marty.com/runbooks/compliance-check-failure"

      - alert: RevenueImpactDropped
        expr: |
          (
            sum(rate(trust_business_revenue_impact_total[1h])) -
            sum(rate(trust_business_revenue_impact_total[1h] offset 24h))
          ) / sum(rate(trust_business_revenue_impact_total[1h] offset 24h)) * 100 < -20
        for: 15m
        labels:
          severity: warning
          service: trust-service
          team: business
        annotations:
          summary: "Revenue impact dropped significantly"
          description: "Revenue impact dropped by {{ $value }}% compared to 24h ago"
          runbook_url: "https://docs.marty.com/runbooks/revenue-drop"

  # === GRPC SERVICE ALERTS ===
  - name: trust-service.grpc
    interval: 60s
    rules:
      - alert: GRPCHighErrorRate
        expr: |
          (
            sum(rate(trust_service_grpc_requests_total{status!="OK"}[5m])) /
            sum(rate(trust_service_grpc_requests_total[5m]))
          ) * 100 > 5
        for: 3m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "High gRPC error rate"
          description: "gRPC error rate is {{ $value }}% for method {{ $labels.method }}"
          runbook_url: "https://docs.marty.com/runbooks/grpc-error-rate"

      - alert: GRPCHighLatency
        expr: |
          histogram_quantile(0.95,
            sum(rate(trust_service_grpc_request_duration_seconds_bucket[5m])) by (le, method)
          ) > 3
        for: 5m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "High gRPC latency"
          description: "gRPC 95th percentile latency for {{ $labels.method }} is {{ $value }}s"
          runbook_url: "https://docs.marty.com/runbooks/grpc-latency"

  # === DATABASE ALERTS ===
  - name: trust-service.database
    interval: 60s
    rules:
      - alert: DatabaseQuerySlow
        expr: |
          histogram_quantile(0.95,
            sum(rate(trust_service_database_query_duration_seconds_bucket[5m])) by (le, operation)
          ) > 1
        for: 5m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "Slow database queries"
          description: "95th percentile query time for {{ $labels.operation }} is {{ $value }}s"
          runbook_url: "https://docs.marty.com/runbooks/slow-database-queries"

      - alert: DatabaseErrorRate
        expr: |
          sum(rate(trust_service_database_errors_total[5m])) > 0
        for: 2m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "Database errors detected"
          description: "Database {{ $labels.error_type }} errors: {{ $value }} errors/sec"
          runbook_url: "https://docs.marty.com/runbooks/database-errors"

      - alert: DatabaseConnectionPoolExhaustion
        expr: |
          trust_service_database_connections_active /
          on() scalar(max(trust_service_database_connections_active)) > 0.9
        for: 5m
        labels:
          severity: critical
          service: trust-service
          team: platform
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "Database connection pool usage is {{ $value }}%"
          runbook_url: "https://docs.marty.com/runbooks/connection-pool-exhaustion"

  # === INFRASTRUCTURE HEALTH ALERTS ===
  - name: trust-service.infrastructure
    interval: 120s
    rules:
      - alert: HighMemoryPressure
        expr: |
          (
            sum(trust_service_memory_usage_bytes{type="used"}) /
            sum(trust_service_memory_usage_bytes{type="total"})
          ) > 0.9
        for: 5m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "High memory pressure"
          description: "Memory usage is {{ $value }}%"
          runbook_url: "https://docs.marty.com/runbooks/memory-pressure"

      - alert: DiskSpaceLow
        expr: |
          (
            sum(trust_service_disk_usage_bytes{type="used"}) /
            sum(trust_service_disk_usage_bytes{type="total"})
          ) > 0.85
        for: 10m
        labels:
          severity: warning
          service: trust-service
          team: platform
        annotations:
          summary: "Low disk space"
          description: "Disk usage is {{ $value }}%"
          runbook_url: "https://docs.marty.com/runbooks/disk-space-low"

  # === ESCALATION RULES ===
  - name: trust-service.escalation
    interval: 300s
    rules:
      - alert: CriticalAlertDuration
        expr: |
          ALERTS{alertname!="CriticalAlertDuration",severity="critical"} == 1
        for: 15m
        labels:
          severity: critical
          service: trust-service
          team: platform
          escalation: "true"
        annotations:
          summary: "Critical alert {{ $labels.alertname }} ongoing for 15+ minutes"
          description: "Critical alert {{ $labels.alertname }} has been firing for more than 15 minutes"
          runbook_url: "https://docs.marty.com/runbooks/escalation-procedures"

      - alert: MultipleSystemFailures
        expr: |
          count(ALERTS{service="trust-service",severity="critical"} == 1) > 3
        for: 5m
        labels:
          severity: critical
          service: trust-service
          team: platform
          escalation: "true"
        annotations:
          summary: "Multiple critical system failures"
          description: "{{ $value }} critical alerts are firing simultaneously"
          runbook_url: "https://docs.marty.com/runbooks/multiple-failures"
