# Lightweight Kind configuration for CI/CD pipeline testing
# Optimized for fast startup and minimal resource usage
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# Cluster name for CI identification
name: marty-ci

# Minimal node configuration for CI
nodes:
  # Single control-plane node for CI efficiency
  - role: control-plane
    image: kindest/node:v1.28.0
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "marty.ci/role=control-plane"
            # Faster CI startup
            max-pods: "50"
    
  # Single worker for plugin testing
  - role: worker
    image: kindest/node:v1.28.0
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "marty.ci/role=worker,marty.ci/plugin-test=true"
            max-pods: "50"

# Minimal networking for CI
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"

# Essential feature gates for CI testing
featureGates:
  "ServerSideApply": true
  "CustomResourceValidationExpressions": true

# Fast startup configuration
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        # Minimal logging for CI
        v: "2"
    controllerManager:
      extraArgs:
        # Fast reconciliation for CI
        concurrent-deployment-syncs: "1"
    scheduler:
      extraArgs:
        # Simple scheduling for CI
        v: "2"