# ConfigMap for Marty MMF Plugin configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: marty-plugin-config
  namespace: marty-mmf
  labels:
    app.kubernetes.io/name: marty-mmf-plugin
    app.kubernetes.io/component: config
    app.kubernetes.io/version: "1.0.0"
    mmf.plugin/name: marty
data:
  # Plugin configuration
  plugin.yaml: |
    name: marty
    enabled: true
    type: trust-pki
    version: "1.0.0"
    description: "ICAO-compliant PKI and trust services for digital identity documents"
    
    # Plugin-specific configuration
    config:
      # Trust Anchor Service
      trust_anchor:
        url: "${TRUST_ANCHOR_URL:-http://trust-anchor-service:8080}"
        validation_enabled: true
        cache_ttl_hours: 24
        
      # PKD Service  
      pkd:
        url: "${PKD_URL:-http://pkd-service:8080}"
        sync_interval_hours: 24
        max_cache_size: 10000
        
      # Document Signer Service
      document_signer:
        url: "${SIGNER_URL:-http://document-signer-service:8080}"
        algorithms: ["RSA-SHA256", "ECDSA-SHA256"]
        key_rotation_days: 365
        
      # CSCA Service
      csca:
        url: "${CSCA_URL:-http://csca-service:8080}"
        certificate_validation: true
        crl_check_enabled: true
        
      # Observability
      observability:
        metrics_enabled: true
        tracing_enabled: true
        health_check_interval: 30
        log_level: "INFO"
  
  # Environment-specific settings
  development.yaml: |
    environment: development
    debug: true
    log_level: "DEBUG"
    
    # Development-specific overrides
    config:
      trust_anchor:
        validation_enabled: false  # Relaxed for dev
      observability:
        log_level: "DEBUG"
        metrics_interval: 10
  
  production.yaml: |
    environment: production
    debug: false
    log_level: "INFO"
    
    # Production-specific settings
    config:
      trust_anchor:
        validation_enabled: true
        cache_ttl_hours: 48
      observability:
        log_level: "INFO"
        metrics_interval: 60

---
# Secret for sensitive plugin configuration
apiVersion: v1
kind: Secret
metadata:
  name: marty-plugin-secrets
  namespace: marty-mmf
  labels:
    app.kubernetes.io/name: marty-mmf-plugin
    app.kubernetes.io/component: secrets
    mmf.plugin/name: marty
type: Opaque
data:
  # Base64 encoded secrets (these would be real secrets in production)
  # Example: echo -n "your-secret-value" | base64
  trust-anchor-api-key: ZGV2ZWxvcG1lbnQtYXBpLWtleQ==  # development-api-key
  pkd-api-key: ZGV2ZWxvcG1lbnQtcGtkLWtleQ==          # development-pkd-key
  signer-private-key: ZGV2ZWxvcG1lbnQtc2lnbmVyLWtleQ==  # development-signer-key
  csca-api-key: ZGV2ZWxvcG1lbnQtY3NjYS1rZXk=          # development-csca-key