# Ingress for Marty MMF Plugin (development)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marty-plugin-ingress
  namespace: marty-mmf
  labels:
    app.kubernetes.io/name: marty-mmf-plugin
    app.kubernetes.io/component: ingress
    mmf.plugin/name: marty
    environment: development
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # Plugin-specific annotations
    mmf.plugin/type: "trust-pki"
    mmf.plugin/version: "1.0.0"
spec:
  rules:
  - host: marty-plugin.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: marty-mmf-plugin-service
            port:
              number: 8080
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: marty-mmf-plugin-service
            port:
              number: 8081
  - host: marty-grpc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: marty-mmf-plugin-service
            port:
              number: 9090

---
# HorizontalPodAutoscaler for plugin scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: marty-plugin-hpa
  namespace: marty-mmf
  labels:
    app.kubernetes.io/name: marty-mmf-plugin
    app.kubernetes.io/component: autoscaling
    mmf.plugin/name: marty
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: marty-mmf-plugin
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60

---
# PodDisruptionBudget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: marty-plugin-pdb
  namespace: marty-mmf
  labels:
    app.kubernetes.io/name: marty-mmf-plugin
    app.kubernetes.io/component: availability
    mmf.plugin/name: marty
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: marty-mmf-plugin
      mmf.plugin/name: marty

---
# NetworkPolicy for plugin security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: marty-plugin-netpol
  namespace: marty-mmf
  labels:
    app.kubernetes.io/name: marty-mmf-plugin
    app.kubernetes.io/component: security
    mmf.plugin/name: marty
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: marty-mmf-plugin
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from other pods in the namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: marty-mmf
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 9090
  # Allow ingress from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8081
  egress:
  # Allow DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
  # Allow outbound HTTPS for external PKI services
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow communication within namespace
  - to:
    - namespaceSelector:
        matchLabels:
          name: marty-mmf