# Default values for marty-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: marty
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  healthPort: 8081

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

config:
  database:
    host: ""
    port: 5432
    name: ""
    user: ""
    password: ""
  kafka:
    brokers: ""
    topicPrefix: ""
  redis:
    host: ""
    port: 6379

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

nodeSelector: {}

tolerations: []

affinity: {}

# OpenXPKI integration (for services that require it)
# IMPORTANT: Credentials are REQUIRED when enabled. No defaults provided for security.
openxpki:
  enabled: false
  baseUrl: "https://openxpki.example.com/api/v2"
  realm: "marty"
  verifySSL: false
  # Credentials configuration (REQUIRED when enabled)
  credentials:
    # Option 1: Reference existing secret containing credentials
    # Expected keys: username, password
    existingSecret: ""
    # Option 2: Use secret files (for Docker secrets, Vault Agent, etc.)
    # Set to true to use *_FILE environment pattern
    useSecretFiles: false
    # Paths to secret files (when useSecretFiles: true)
    usernameFile: "/run/secrets/openxpki_username"
    passwordFile: "/run/secrets/openxpki_password"
  # Local trust store sync path (mounted volume / emptyDir in future enhancement)
  localStorePath: "/data/trust/openxpki_sync"