# Security Automation Configuration for CI/CD Integration
# Defines automated security checks and their enforcement policies

automation:
  # CI/CD Pipeline Integration
  pipeline:
    # Security gates in the pipeline
    security_gates:
      # Pre-commit hooks
      pre_commit:
        enabled: true
        mandatory: true
        checks:
          - "secrets_detection"
          - "dependency_scan"
          - "code_analysis"
          - "configuration_validation"
        failure_action: "block"
        
      # Build-time security checks
      build_time:
        enabled: true
        mandatory: true
        checks:
          - "container_scan"
          - "dependency_audit"
          - "static_analysis"
          - "license_compliance"
        failure_threshold: "high"
        
      # Pre-deployment security validation
      pre_deployment:
        enabled: true
        mandatory: true
        checks:
          - "penetration_test"
          - "compliance_check"
          - "security_review"
          - "vulnerability_assessment"
        approval_required: true
        
      # Post-deployment monitoring
      post_deployment:
        enabled: true
        checks:
          - "runtime_security"
          - "access_monitoring"
          - "anomaly_detection"
          - "compliance_monitoring"
        alert_threshold: "medium"

    # Failure handling
    failure_handling:
      # Action on security check failure
      high_severity: "block_deployment"
      medium_severity: "require_approval"
      low_severity: "log_and_continue"
      
      # Notification settings
      notifications:
        channels: ["slack", "email", "pagerduty"]
        recipients:
          slack: "#security-alerts"
          email: ["security@marty-platform.com", "devops@marty-platform.com"]
          pagerduty: "security-team"
          
      # Escalation procedures
      escalation:
        timeout_minutes: 30
        escalation_levels:
          level_1: ["security_analyst"]
          level_2: ["security_manager", "tech_lead"]
          level_3: ["ciso", "cto"]

  # Automated Security Testing
  testing:
    # Static Application Security Testing (SAST)
    sast:
      enabled: true
      tools:
        - name: "bandit"
          config: "config/security/bandit.yaml"
          severity_threshold: "medium"
          
        - name: "semgrep"
          ruleset: "p/security-audit"
          severity_threshold: "high"
          
        - name: "codeql"
          language: "python"
          query_suite: "security-extended"
          
      schedule: "on_commit"
      report_format: ["json", "sarif"]
      
    # Dynamic Application Security Testing (DAST)
    dast:
      enabled: true
      tools:
        - name: "zap"
          spider_timeout: 300
          scan_timeout: 600
          authentication: "form_based"
          
        - name: "burp"
          scan_type: "passive"
          crawl_depth: 3
          
      schedule: "nightly"
      target_environments: ["staging", "pre-production"]
      
    # Interactive Application Security Testing (IAST)
    iast:
      enabled: false  # Enable when ready for runtime analysis
      tools:
        - name: "contrast"
          agent_config: "runtime_monitoring"
          
      environments: ["staging"]
      
    # Software Composition Analysis (SCA)
    sca:
      enabled: true
      tools:
        - name: "safety"
          database_url: "https://pyup.io/safety/api/v1/"
          ignore_list: []
          
        - name: "pip-audit"
          vulnerability_db: "osv"
          
        - name: "snyk"
          org: "marty-platform"
          project_id: "marty-backend"
          
      schedule: "daily"
      auto_fix: "low_risk_only"
      
    # Container Security Scanning
    container_scanning:
      enabled: true
      tools:
        - name: "trivy"
          image_scan: true
          filesystem_scan: true
          vulnerability_db: "ghcr.io/aquasecurity/trivy-db"
          
        - name: "clair"
          api_endpoint: "http://clair:6060"
          
        - name: "snyk"
          container_monitoring: true
          
      schedule: "on_build"
      severity_threshold: "high"
      
    # Infrastructure as Code (IaC) Security
    iac_security:
      enabled: true
      tools:
        - name: "checkov"
          framework: ["terraform", "kubernetes", "docker"]
          soft_fail: false
          
        - name: "terrascan"
          policy_type: "all"
          
        - name: "kube-score"
          kubernetes_version: "1.28"
          
      schedule: "on_commit"
      policy_as_code: true

  # Automated Remediation
  remediation:
    # Dependency updates
    dependency_updates:
      enabled: true
      auto_merge: "patch_only"
      security_updates: "always"
      schedule: "weekly"
      
    # Code fixes
    code_fixes:
      enabled: false  # Requires human review
      fix_types: ["formatting", "import_sorting"]
      
    # Configuration updates
    config_updates:
      enabled: true
      security_configs: "auto_apply"
      policy_updates: "manual_review"

  # Monitoring and Alerting
  monitoring:
    # Real-time security monitoring
    real_time:
      enabled: true
      metrics:
        - "failed_authentication_rate"
        - "privilege_escalation_attempts"
        - "unusual_access_patterns"
        - "data_exfiltration_indicators"
        - "malware_detection"
        
    # Security dashboards
    dashboards:
      enabled: true
      tools:
        - name: "grafana"
          datasource: "prometheus"
          dashboard_config: "monitoring/grafana/security_dashboard.json"
          
        - name: "elk"
          index_pattern: "security-logs-*"
          dashboard_config: "monitoring/kibana/security_dashboard.json"
          
    # Alerting rules
    alerting:
      enabled: true
      channels: ["slack", "pagerduty", "email"]
      rules:
        critical:
          - "security_breach_detected"
          - "privilege_escalation_successful"
          - "data_exfiltration_confirmed"
          response_time: "immediate"
          
        high:
          - "multiple_failed_logins"
          - "suspicious_api_access"
          - "configuration_tampering"
          response_time: "15_minutes"
          
        medium:
          - "unusual_login_location"
          - "deprecated_api_usage"
          - "policy_violation"
          response_time: "1_hour"

  # Compliance Automation
  compliance:
    # Automated compliance checks
    checks:
      enabled: true
      frameworks:
        - name: "owasp_top_10"
          version: "2021"
          
        - name: "nist_csf"
          version: "1.1"
          
        - name: "iso_27001"
          version: "2013"
          
        - name: "soc2_type2"
          controls: ["cc1", "cc2", "cc3", "cc4", "cc5", "cc6", "cc7"]
          
      schedule: "weekly"
      report_generation: true
      
    # Evidence collection
    evidence_collection:
      enabled: true
      types:
        - "security_logs"
        - "access_logs"
        - "configuration_snapshots"
        - "policy_documents"
        - "training_records"
      retention_period: "7_years"
      encryption: true
      
    # Audit trail
    audit_trail:
      enabled: true
      immutable: true
      blockchain_verification: false
      third_party_verification: true

# Environment-specific configurations
environments:
  development:
    automation:
      pipeline:
        security_gates:
          pre_commit:
            mandatory: false
          build_time:
            failure_threshold: "critical"
      testing:
        dast:
          enabled: false
        container_scanning:
          severity_threshold: "critical"
          
  staging:
    automation:
      testing:
        dast:
          enabled: true
          target_environments: ["staging"]
        iast:
          enabled: true
          
  production:
    automation:
      pipeline:
        security_gates:
          pre_deployment:
            approval_required: true
            mandatory: true
      monitoring:
        real_time:
          enabled: true
        alerting:
          response_time_multiplier: 0.5  # Faster response in prod