# Bandit Security Configuration for Marty Platform
# Customizes security analysis rules and exclusions

# Tests to skip (use test IDs or names)
skips:
  # Skip tests that are not applicable or generate false positives
  - B101  # assert_used - asserts are OK in test files
  - B601  # paramiko_calls - if using paramiko for legitimate SSH operations
  - B602  # subprocess_popen_with_shell_equals_true - when shell=True is necessary

# Tests to run (if you want to specify only certain tests)
# tests: [B101, B102, B103]

# Confidence levels to report
# Options: LOW, MEDIUM, HIGH
confidence: MEDIUM

# Severity levels to report
# Options: LOW, MEDIUM, HIGH
severity: MEDIUM

# Paths to exclude from scanning
exclude_dirs:
  - /tests/
  - /test_/
  - /.pytest_cache/
  - /.venv/
  - /venv/
  - /.tox/
  - /build/
  - /dist/

# File patterns to exclude
exclude:
  - "*/test_*.py"
  - "*/tests.py"
  - "*_test.py"
  - "*/conftest.py"
  - "*/migrations/*"

# Custom test plugins (if any)
# plugins: []

# Baseline file for tracking existing issues
# baseline: .bandit_baseline

# Output formats
# Available: csv, custom, html, json, screen, txt, xml, yaml
# format: json

# Additional configuration for specific tests
rules:
  # B104: hardcoded_bind_all_interfaces
  B104:
    # Allow binding to all interfaces in development
    bind_all_interfaces: false

  # B105: hardcoded_password_string
  B105:
    # Words that trigger this test
    word_list:
      - password
      - pass
      - passwd
      - pwd
      - secret
      - token
      - key
      - api_key
      - auth_token
      - access_token

  # B106: hardcoded_password_funcarg
  B106:
    # Function argument names that trigger this test
    function_names:
      - password
      - pass
      - passwd
      - pwd
      - secret
      - token

  # B107: hardcoded_password_default
  B107:
    # Default argument names that trigger this test
    function_names:
      - password
      - pass
      - passwd
      - pwd
      - secret
      - token

  # B201: flask_debug_true
  B201:
    # Skip if debug mode is needed for development
    debug_mode_allowed: false

  # B301: pickle
  B301:
    # Allow pickle usage with warning
    pickle_allowed: false

  # B403: import_pickle
  B403:
    # Allow pickle imports with warning
    pickle_import_allowed: false

  # B501: request_with_no_cert_validation
  B501:
    # Require certificate validation
    cert_validation_required: true

  # B502: ssl_with_bad_version
  B502:
    # Minimum TLS version
    min_tls_version: "1.2"

  # B503: ssl_with_bad_defaults
  B503:
    # Require secure SSL defaults
    secure_ssl_required: true

  # B504: ssl_with_no_version
  B504:
    # Require explicit SSL version
    ssl_version_required: true

  # B505: weak_cryptographic_key
  B505:
    # Minimum key sizes
    min_rsa_key_size: 2048
    min_dsa_key_size: 2048
    min_ec_key_size: 256

  # B506: yaml_load
  B506:
    # Require safe YAML loading
    safe_yaml_required: true

  # B601: paramiko_calls
  B601:
    # Allow paramiko for legitimate use cases
    paramiko_allowed: true

  # B602: subprocess_popen_with_shell_equals_true
  B602:
    # Warn about shell=True usage
    shell_true_allowed: false

  # B603: subprocess_without_shell_equals_true
  B603:
    # Check subprocess calls without shell=True
    check_subprocess: true

  # B604: any_other_function_with_shell_equals_true
  B604:
    # Functions to check for shell=True
    shell_functions:
      - os.system
      - os.popen
      - subprocess.call
      - subprocess.run
      - subprocess.Popen

  # B605: start_process_with_a_shell
  B605:
    # Process starting functions to check
    process_functions:
      - os.startfile
      - os.spawnl
      - os.spawnle
      - os.spawnlp
      - os.spawnlpe
      - os.spawnv
      - os.spawnve
      - os.spawnvp
      - os.spawnvpe

  # B701: jinja2_autoescape_false
  B701:
    # Require Jinja2 autoescape
    jinja2_autoescape_required: true

  # B702: use_of_mako_templates
  B702:
    # Allow Mako templates with warning
    mako_allowed: false

# Per-file configuration
file_rules:
  # Configuration files can have hardcoded values
  "*/config/*":
    skips: [B105, B106, B107]

  # Test files have relaxed rules
  "*/tests/*":
    skips: [B101, B105, B106, B107, B301, B403, B501, B506]

  # Development-specific files
  "*/dev/*":
    skips: [B201, B501]

  # Scripts may need shell commands
  "*/scripts/*":
    skips: [B602, B603, B604, B605]

# Custom plugins or extensions
plugins: []

# Report configuration
report:
  # Include confidence level in output
  include_confidence: true

  # Include severity level in output
  include_severity: true

  # Include line numbers
  include_lineno: true

  # Include issue details
  include_test_details: true

  # Sort by severity
  sort_by_severity: true

# Integration with other tools
integration:
  # Pre-commit hook configuration
  pre_commit:
    enabled: true
    args: ["-f", "custom", "--msg-template", "{abspath}:{line}: {test_id}[bandit]: {severity}: {msg}"]

  # CI/CD integration
  ci_cd:
    enabled: true
    fail_on_high: true
    fail_on_medium: false
    fail_on_low: false

  # IDE integration
  ide:
    enabled: true
    format: "json"
