apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: marty-inter-service-authz
  namespace: marty
spec:
  server:
    name: marty-grpc-server
  requiredRoutes:
  - pathRegex: "/.*"
    methods: ["*"]
  client:
    meshTLS:
      serviceAccounts:
      - name: trust-svc
      - name: pkd-service
      - name: credential-ledger
      - name: inspection-system
      - name: document-signer
      - name: csca-service
      - name: trust-anchor
      - name: mdl-engine
      - name: mdoc-engine
      - name: passport-engine
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: marty-http-authz
  namespace: marty
spec:
  server:
    name: marty-http-server
  requiredRoutes:
  - pathRegex: "/.*"
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
  client:
    meshTLS:
      serviceAccounts:
      - name: trust-svc
      - name: pkd-service
      - name: credential-ledger
      - name: inspection-system
      - name: document-signer
      - name: csca-service
      - name: trust-anchor
      - name: mdl-engine
      - name: mdoc-engine
      - name: passport-engine
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: marty-metrics-authz
  namespace: marty
spec:
  server:
    name: marty-metrics-server
  requiredRoutes:
  - pathRegex: "/metrics"
    methods: ["GET"]
  - pathRegex: "/health/.*"
    methods: ["GET"]
  client:
    # Allow Prometheus and health checkers
    unauthenticated: true
