apiVersion: v1
kind: ConfigMap
metadata:
  name: trust-svc-config
  namespace: marty
  labels:
    app: trust-svc
    component: config
data:
  trust-service.yaml: |
    database:
      host: postgres
      port: 5432
      name: martydb
      user: martyuser
      password: martypassword
      pool_size: 20
      max_overflow: 10
      echo: false
    
    service:
      host: 0.0.0.0
      port: 8080
      log_level: INFO
      workers: 4
    
    pkd:
      refresh_interval: 3600
      icao_url: "https://pkddownloadsg.icao.int"
      sources:
        - name: "icao_official"
          url: "https://pkddownloadsg.icao.int"
          type: "http"
          enabled: true
    
    kms:
      region: us-east-1
      key_id: ""
    
    metrics:
      enabled: true
      port: 8080
      path: /metrics