apiVersion: v1
kind: ServiceAccount
metadata:
  name: trust-svc
  namespace: marty
  labels:
    app: trust-svc
    component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trust-svc
  labels:
    app: trust-svc
    component: rbac
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trust-svc
  labels:
    app: trust-svc
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trust-svc
subjects:
- kind: ServiceAccount
  name: trust-svc
  namespace: marty